/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.alogram.payrisk.v1.models.AvsResultEnum;
import com.alogram.payrisk.v1.models.CardNetworkEnum;
import com.alogram.payrisk.v1.models.CvvResultEnum;
import com.alogram.payrisk.v1.models.PaymentCardTypeEnum;
import com.alogram.payrisk.v1.models.ScaMethodEnum;
import com.alogram.payrisk.v1.models.ThreeDSData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Card
 */
class CardTest {
    private final Card model = new Card();

    /**
     * Model tests for Card
     */
    @Test
    void testCard() {
        // TODO: test Card
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'cardNetwork'
     */
    @Test
    void cardNetworkTest() {
        // TODO: test cardNetwork
    }

    /**
     * Test the property 'cardType'
     */
    @Test
    void cardTypeTest() {
        // TODO: test cardType
    }

    /**
     * Test the property 'bin'
     */
    @Test
    void binTest() {
        // TODO: test bin
    }

    /**
     * Test the property 'issuerCountry'
     */
    @Test
    void issuerCountryTest() {
        // TODO: test issuerCountry
    }

    /**
     * Test the property 'avsResult'
     */
    @Test
    void avsResultTest() {
        // TODO: test avsResult
    }

    /**
     * Test the property 'cvvResult'
     */
    @Test
    void cvvResultTest() {
        // TODO: test cvvResult
    }

    /**
     * Test the property 'scaMethod'
     */
    @Test
    void scaMethodTest() {
        // TODO: test scaMethod
    }

    /**
     * Test the property 'threeDS'
     */
    @Test
    void threeDSTest() {
        // TODO: test threeDS
    }

}
