/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.alogram.payrisk.v1.models.EntityIds;
import com.alogram.payrisk.v1.models.Identity;
import com.alogram.payrisk.v1.models.Purchase;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CheckRequest
 */
class CheckRequestTest {
    private final CheckRequest model = new CheckRequest();

    /**
     * Model tests for CheckRequest
     */
    @Test
    void testCheckRequest() {
        // TODO: test CheckRequest
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'paymentIntentId'
     */
    @Test
    void paymentIntentIdTest() {
        // TODO: test paymentIntentId
    }

    /**
     * Test the property 'entities'
     */
    @Test
    void entitiesTest() {
        // TODO: test entities
    }

    /**
     * Test the property 'purchase'
     */
    @Test
    void purchaseTest() {
        // TODO: test purchase
    }

    /**
     * Test the property 'identity'
     */
    @Test
    void identityTest() {
        // TODO: test identity
    }

}
