/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.alogram.payrisk.v1.models.FraudScore;
import com.alogram.payrisk.v1.models.ReasonDetail;
import com.alogram.payrisk.v1.models.RiskBreakdown;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DecisionResponse
 */
class DecisionResponseTest {
    private final DecisionResponse model = new DecisionResponse();

    /**
     * Model tests for DecisionResponse
     */
    @Test
    void testDecisionResponse() {
        // TODO: test DecisionResponse
    }

    /**
     * Test the property 'assessmentId'
     */
    @Test
    void assessmentIdTest() {
        // TODO: test assessmentId
    }

    /**
     * Test the property 'decision'
     */
    @Test
    void decisionTest() {
        // TODO: test decision
    }

    /**
     * Test the property 'decisionAt'
     */
    @Test
    void decisionAtTest() {
        // TODO: test decisionAt
    }

    /**
     * Test the property 'riskScore'
     */
    @Test
    void riskScoreTest() {
        // TODO: test riskScore
    }

    /**
     * Test the property 'fraudScore'
     */
    @Test
    void fraudScoreTest() {
        // TODO: test fraudScore
    }

    /**
     * Test the property 'breakdown'
     */
    @Test
    void breakdownTest() {
        // TODO: test breakdown
    }

    /**
     * Test the property 'reasonCodes'
     */
    @Test
    void reasonCodesTest() {
        // TODO: test reasonCodes
    }

    /**
     * Test the property 'reasons'
     */
    @Test
    void reasonsTest() {
        // TODO: test reasons
    }

    /**
     * Test the property 'actions'
     */
    @Test
    void actionsTest() {
        // TODO: test actions
    }

    /**
     * Test the property 'paymentIntentId'
     */
    @Test
    void paymentIntentIdTest() {
        // TODO: test paymentIntentId
    }

    /**
     * Test the property 'policyVersion'
     */
    @Test
    void policyVersionTest() {
        // TODO: test policyVersion
    }

    /**
     * Test the property 'modelVersion'
     */
    @Test
    void modelVersionTest() {
        // TODO: test modelVersion
    }

    /**
     * Test the property 'ttlSeconds'
     */
    @Test
    void ttlSecondsTest() {
        // TODO: test ttlSeconds
    }

}
