/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EntityIds
 */
class EntityIdsTest {
    private final EntityIds model = new EntityIds();

    /**
     * Model tests for EntityIds
     */
    @Test
    void testEntityIds() {
        // TODO: test EntityIds
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'endCustomerId'
     */
    @Test
    void endCustomerIdTest() {
        // TODO: test endCustomerId
    }

    /**
     * Test the property 'memberId'
     */
    @Test
    void memberIdTest() {
        // TODO: test memberId
    }

    /**
     * Test the property 'paymentInstrumentId'
     */
    @Test
    void paymentInstrumentIdTest() {
        // TODO: test paymentInstrumentId
    }

    /**
     * Test the property 'deviceId'
     */
    @Test
    void deviceIdTest() {
        // TODO: test deviceId
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'emailHash'
     */
    @Test
    void emailHashTest() {
        // TODO: test emailHash
    }

    /**
     * Test the property 'emailDomainHash'
     */
    @Test
    void emailDomainHashTest() {
        // TODO: test emailDomainHash
    }

    /**
     * Test the property 'phoneHash'
     */
    @Test
    void phoneHashTest() {
        // TODO: test phoneHash
    }

    /**
     * Test the property 'shippingAddressHash'
     */
    @Test
    void shippingAddressHashTest() {
        // TODO: test shippingAddressHash
    }

    /**
     * Test the property 'billingAddressHash'
     */
    @Test
    void billingAddressHashTest() {
        // TODO: test billingAddressHash
    }

}
