/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.alogram.payrisk.v1.models.PostalAddress;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Identity
 */
class IdentityTest {
    private final Identity model = new Identity();

    /**
     * Model tests for Identity
     */
    @Test
    void testIdentity() {
        // TODO: test Identity
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'emailDomain'
     */
    @Test
    void emailDomainTest() {
        // TODO: test emailDomain
    }

    /**
     * Test the property 'phone'
     */
    @Test
    void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'shippingAddress'
     */
    @Test
    void shippingAddressTest() {
        // TODO: test shippingAddress
    }

    /**
     * Test the property 'billingAddress'
     */
    @Test
    void billingAddressTest() {
        // TODO: test billingAddress
    }

}
