/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.alogram.payrisk.v1.models.DeviceInfo;
import com.alogram.payrisk.v1.models.InteractionTypeEnum;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Interaction
 */
class InteractionTest {
    private final Interaction model = new Interaction();

    /**
     * Model tests for Interaction
     */
    @Test
    void testInteraction() {
        // TODO: test Interaction
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'deviceInfo'
     */
    @Test
    void deviceInfoTest() {
        // TODO: test deviceInfo
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'interactionType'
     */
    @Test
    void interactionTypeTest() {
        // TODO: test interactionType
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

}
