/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Integrity
 */
class IntegrityTest {
    private final Integrity model = new Integrity();

    /**
     * Model tests for Integrity
     */
    @Test
    void testIntegrity() {
        // TODO: test Integrity
    }

    /**
     * Test the property 'isProxyVpnTor'
     */
    @Test
    void isProxyVpnTorTest() {
        // TODO: test isProxyVpnTor
    }

    /**
     * Test the property 'isHostingProvider'
     */
    @Test
    void isHostingProviderTest() {
        // TODO: test isHostingProvider
    }

    /**
     * Test the property 'isHeadless'
     */
    @Test
    void isHeadlessTest() {
        // TODO: test isHeadless
    }

    /**
     * Test the property 'isAutomation'
     */
    @Test
    void isAutomationTest() {
        // TODO: test isAutomation
    }

    /**
     * Test the property 'isEmulator'
     */
    @Test
    void isEmulatorTest() {
        // TODO: test isEmulator
    }

    /**
     * Test the property 'isRootedJailbroken'
     */
    @Test
    void isRootedJailbrokenTest() {
        // TODO: test isRootedJailbroken
    }

}
