/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.alogram.payrisk.v1.models.Account;
import com.alogram.payrisk.v1.models.EntityIds;
import com.alogram.payrisk.v1.models.KycPayload;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for KycCheckRequest
 */
class KycCheckRequestTest {
    private final KycCheckRequest model = new KycCheckRequest();

    /**
     * Model tests for KycCheckRequest
     */
    @Test
    void testKycCheckRequest() {
        // TODO: test KycCheckRequest
    }

    /**
     * Test the property 'eventSubtype'
     */
    @Test
    void eventSubtypeTest() {
        // TODO: test eventSubtype
    }

    /**
     * Test the property 'entities'
     */
    @Test
    void entitiesTest() {
        // TODO: test entities
    }

    /**
     * Test the property 'account'
     */
    @Test
    void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'kyc'
     */
    @Test
    void kycTest() {
        // TODO: test kyc
    }

}
