/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.alogram.payrisk.v1.models.PaymentAuthorizationOutcome;
import com.alogram.payrisk.v1.models.PaymentCaptureOutcome;
import com.alogram.payrisk.v1.models.PaymentChargeback;
import com.alogram.payrisk.v1.models.PaymentChargebackOutcome;
import com.alogram.payrisk.v1.models.PaymentDisputeOutcome;
import com.alogram.payrisk.v1.models.PaymentRefundOutcome;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentOutcome
 */
class PaymentOutcomeTest {
    private final PaymentOutcome model = new PaymentOutcome();

    /**
     * Model tests for PaymentOutcome
     */
    @Test
    void testPaymentOutcome() {
        // TODO: test PaymentOutcome
    }

    /**
     * Test the property 'authorization'
     */
    @Test
    void authorizationTest() {
        // TODO: test authorization
    }

    /**
     * Test the property 'capture'
     */
    @Test
    void captureTest() {
        // TODO: test capture
    }

    /**
     * Test the property 'refund'
     */
    @Test
    void refundTest() {
        // TODO: test refund
    }

    /**
     * Test the property 'dispute'
     */
    @Test
    void disputeTest() {
        // TODO: test dispute
    }

    /**
     * Test the property 'chargeback'
     */
    @Test
    void chargebackTest() {
        // TODO: test chargeback
    }

    /**
     * Test the property 'chargebackOutcome'
     */
    @Test
    void chargebackOutcomeTest() {
        // TODO: test chargebackOutcome
    }

}
