/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.alogram.payrisk.v1.models.ChannelEnum;
import com.alogram.payrisk.v1.models.DeviceInfo;
import com.alogram.payrisk.v1.models.EntryMethodEnum;
import com.alogram.payrisk.v1.models.MerchantContext;
import com.alogram.payrisk.v1.models.OrderContext;
import com.alogram.payrisk.v1.models.PayerTypeEnum;
import com.alogram.payrisk.v1.models.PaymentMethod;
import com.alogram.payrisk.v1.models.StoredCredentialContext;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Purchase
 */
class PurchaseTest {
    private final Purchase model = new Purchase();

    /**
     * Model tests for Purchase
     */
    @Test
    void testPurchase() {
        // TODO: test Purchase
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'deviceInfo'
     */
    @Test
    void deviceInfoTest() {
        // TODO: test deviceInfo
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'channel'
     */
    @Test
    void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'entryMethod'
     */
    @Test
    void entryMethodTest() {
        // TODO: test entryMethod
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'order'
     */
    @Test
    void orderTest() {
        // TODO: test order
    }

    /**
     * Test the property 'payerType'
     */
    @Test
    void payerTypeTest() {
        // TODO: test payerType
    }

    /**
     * Test the property 'storedCredential'
     */
    @Test
    void storedCredentialTest() {
        // TODO: test storedCredential
    }

    /**
     * Test the property 'merchant'
     */
    @Test
    void merchantTest() {
        // TODO: test merchant
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

}
