/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.alogram.payrisk.v1.models.CategorySignal;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RiskBreakdown
 */
class RiskBreakdownTest {
    private final RiskBreakdown model = new RiskBreakdown();

    /**
     * Model tests for RiskBreakdown
     */
    @Test
    void testRiskBreakdown() {
        // TODO: test RiskBreakdown
    }

    /**
     * Test the property 'geography'
     */
    @Test
    void geographyTest() {
        // TODO: test geography
    }

    /**
     * Test the property 'identity'
     */
    @Test
    void identityTest() {
        // TODO: test identity
    }

    /**
     * Test the property 'behavior'
     */
    @Test
    void behaviorTest() {
        // TODO: test behavior
    }

    /**
     * Test the property 'transaction'
     */
    @Test
    void transactionTest() {
        // TODO: test transaction
    }

}
