/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.alogram.payrisk.v1.models.ScoreRecord;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScoresSuccessResponse
 */
class ScoresSuccessResponseTest {
    private final ScoresSuccessResponse model = new ScoresSuccessResponse();

    /**
     * Model tests for ScoresSuccessResponse
     */
    @Test
    void testScoresSuccessResponse() {
        // TODO: test ScoresSuccessResponse
    }

    /**
     * Test the property 'scores'
     */
    @Test
    void scoresTest() {
        // TODO: test scores
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

}
