/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ThreeDSData
 */
class ThreeDSDataTest {
    private final ThreeDSData model = new ThreeDSData();

    /**
     * Model tests for ThreeDSData
     */
    @Test
    void testThreeDSData() {
        // TODO: test ThreeDSData
    }

    /**
     * Test the property 'version'
     */
    @Test
    void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'eci'
     */
    @Test
    void eciTest() {
        // TODO: test eci
    }

    /**
     * Test the property 'flow'
     */
    @Test
    void flowTest() {
        // TODO: test flow
    }

    /**
     * Test the property 'liabilityShift'
     */
    @Test
    void liabilityShiftTest() {
        // TODO: test liabilityShift
    }

    /**
     * Test the property 'cavvPresent'
     */
    @Test
    void cavvPresentTest() {
        // TODO: test cavvPresent
    }

}
