/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.api;

import com.alogram.v1.client.ApiException;
import com.alogram.payrisk.v1.models.AccountCheckRequest;
import com.alogram.payrisk.v1.models.CheckRequest;
import com.alogram.payrisk.v1.models.DecisionResponse;
import com.alogram.payrisk.v1.models.KycCheckRequest;
import com.alogram.payrisk.v1.models.PaymentEvent;
import com.alogram.payrisk.v1.models.Problem;
import com.alogram.payrisk.v1.models.ScoresSuccessResponse;
import com.alogram.payrisk.v1.models.SignalsRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PayriskApi
 */
@Disabled
public class PayriskApiTest {

    private final PayriskApi api = new PayriskApi();

    
    /**
     * Synchronous fraud decision for account/session events (signup, login, settings)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accountRiskCheckTest() throws ApiException {
        String xIdempotencyKey = null;
        AccountCheckRequest accountCheckRequest = null;
        String xTraceId = null;
        DecisionResponse response = 
        api.accountRiskCheck(xIdempotencyKey, accountCheckRequest, xTraceId);
        
        // TODO: test validations
    }
    
    /**
     * Retrieve fraud scores for a customer
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFraudScoresTest() throws ApiException {
        String tenantId = null;
        String xTraceId = null;
        String xIdempotencyKey = null;
        String startTime = null;
        String endTime = null;
        Integer pageSize = null;
        String pageToken = null;
        ScoresSuccessResponse response = 
        api.getFraudScores(tenantId, xTraceId, xIdempotencyKey, startTime, endTime, pageSize, pageToken);
        
        // TODO: test validations
    }
    
    /**
     * Health check for the service
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void healthCheckTest() throws ApiException {
        
        api.healthCheck();
        
        // TODO: test validations
    }
    
    /**
     * Ingest payment lifecycle events (authorization, capture, settlement, refund, dispute, chargeback, chargeback_outcome). 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ingestPaymentEventTest() throws ApiException {
        String xIdempotencyKey = null;
        PaymentEvent paymentEvent = null;
        String xTraceId = null;
        
        api.ingestPaymentEvent(xIdempotencyKey, paymentEvent, xTraceId);
        
        // TODO: test validations
    }
    
    /**
     * Ingest non-payment signals (account or interaction) for modeling
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ingestSignalsTest() throws ApiException {
        String xIdempotencyKey = null;
        SignalsRequest signalsRequest = null;
        String xTraceId = null;
        
        api.ingestSignals(xIdempotencyKey, signalsRequest, xTraceId);
        
        // TODO: test validations
    }
    
    /**
     * Synchronous decision for KYC/identity verification
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void kycRiskCheckTest() throws ApiException {
        String xIdempotencyKey = null;
        KycCheckRequest kycCheckRequest = null;
        String xTraceId = null;
        DecisionResponse response = 
        api.kycRiskCheck(xIdempotencyKey, kycCheckRequest, xTraceId);
        
        // TODO: test validations
    }
    
    /**
     * Synchronous fraud decision for a purchase
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void riskCheckTest() throws ApiException {
        String xIdempotencyKey = null;
        CheckRequest checkRequest = null;
        String xTraceId = null;
        DecisionResponse response = 
        api.riskCheck(xIdempotencyKey, checkRequest, xTraceId);
        
        // TODO: test validations
    }
    
}
