/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.Account;
import com.alogram.payrisk.v1.models.EntityIds;
import com.alogram.payrisk.v1.models.Interaction;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * AccountCheckRequest
 */
@JsonPropertyOrder({
  AccountCheckRequest.JSON_PROPERTY_EVENT_SUBTYPE,
  AccountCheckRequest.JSON_PROPERTY_ENTITIES,
  AccountCheckRequest.JSON_PROPERTY_ACCOUNT,
  AccountCheckRequest.JSON_PROPERTY_INTERACTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class AccountCheckRequest {
  /**
   * The specific subtype of the account event (e.g., &#39;signup&#39;, &#39;login&#39;).
   */
  public enum EventSubtypeEnum {
    SIGNUP(String.valueOf("signup")),
    
    LOGIN(String.valueOf("login")),
    
    PASSWORD_RESET(String.valueOf("password_reset")),
    
    MFA_RESET(String.valueOf("mfa_reset")),
    
    SETTING_CHANGE(String.valueOf("setting_change"));

    private String value;

    EventSubtypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EventSubtypeEnum fromValue(String value) {
      for (EventSubtypeEnum b : EventSubtypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EVENT_SUBTYPE = "eventSubtype";
  @javax.annotation.Nonnull
  private EventSubtypeEnum eventSubtype;

  public static final String JSON_PROPERTY_ENTITIES = "entities";
  @javax.annotation.Nullable
  private EntityIds entities;

  public static final String JSON_PROPERTY_ACCOUNT = "account";
  @javax.annotation.Nullable
  private Account account;

  public static final String JSON_PROPERTY_INTERACTION = "interaction";
  @javax.annotation.Nullable
  private Interaction interaction;

  public AccountCheckRequest() { 
  }

  public AccountCheckRequest eventSubtype(@javax.annotation.Nonnull EventSubtypeEnum eventSubtype) {
    this.eventSubtype = eventSubtype;
    return this;
  }

  /**
   * The specific subtype of the account event (e.g., &#39;signup&#39;, &#39;login&#39;).
   * @return eventSubtype
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVENT_SUBTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EventSubtypeEnum getEventSubtype() {
    return eventSubtype;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_SUBTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventSubtype(@javax.annotation.Nonnull EventSubtypeEnum eventSubtype) {
    this.eventSubtype = eventSubtype;
  }


  public AccountCheckRequest entities(@javax.annotation.Nullable EntityIds entities) {
    this.entities = entities;
    return this;
  }

  /**
   * Get entities
   * @return entities
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntityIds getEntities() {
    return entities;
  }


  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntities(@javax.annotation.Nullable EntityIds entities) {
    this.entities = entities;
  }


  public AccountCheckRequest account(@javax.annotation.Nullable Account account) {
    this.account = account;
    return this;
  }

  /**
   * Get account
   * @return account
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Account getAccount() {
    return account;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccount(@javax.annotation.Nullable Account account) {
    this.account = account;
  }


  public AccountCheckRequest interaction(@javax.annotation.Nullable Interaction interaction) {
    this.interaction = interaction;
    return this;
  }

  /**
   * Get interaction
   * @return interaction
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Interaction getInteraction() {
    return interaction;
  }


  @JsonProperty(JSON_PROPERTY_INTERACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInteraction(@javax.annotation.Nullable Interaction interaction) {
    this.interaction = interaction;
  }


  /**
   * Return true if this AccountCheckRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountCheckRequest accountCheckRequest = (AccountCheckRequest) o;
    return Objects.equals(this.eventSubtype, accountCheckRequest.eventSubtype) &&
        Objects.equals(this.entities, accountCheckRequest.entities) &&
        Objects.equals(this.account, accountCheckRequest.account) &&
        Objects.equals(this.interaction, accountCheckRequest.interaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventSubtype, entities, account, interaction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountCheckRequest {\n");
    sb.append("    eventSubtype: ").append(toIndentedString(eventSubtype)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    interaction: ").append(toIndentedString(interaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `eventSubtype` to the URL query string
    if (getEventSubtype() != null) {
      joiner.add(String.format("%seventSubtype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventSubtype()))));
    }

    // add `entities` to the URL query string
    if (getEntities() != null) {
      joiner.add(getEntities().toUrlQueryString(prefix + "entities" + suffix));
    }

    // add `account` to the URL query string
    if (getAccount() != null) {
      joiner.add(getAccount().toUrlQueryString(prefix + "account" + suffix));
    }

    // add `interaction` to the URL query string
    if (getInteraction() != null) {
      joiner.add(getInteraction().toUrlQueryString(prefix + "interaction" + suffix));
    }

    return joiner.toString();
  }
}
