/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AVS response codes: Y: Address and 5-digit ZIP match N: Address and 5-digit ZIP do not match A: Address matches, ZIP does not Z: ZIP matches, address does not U: Address unavailable R: System unavailable S: Not supported G: Global non-AVS B: International AVS C: Street address and postal code not verified due to incompatible formats D: Street address and postal code not verified due to incompatible formats M: Street address and postal code match P: Street address not verified. Postal code matches. X: Street address and 9-digit ZIP match W: Street address not verified. 9-digit ZIP matches. 
 */
public enum AvsResultEnum {
  
  Y("Y"),
  
  N("N"),
  
  A("A"),
  
  Z("Z"),
  
  U("U"),
  
  R("R"),
  
  S("S"),
  
  G("G"),
  
  B("B"),
  
  C("C"),
  
  D("D"),
  
  M("M"),
  
  P("P"),
  
  X("X"),
  
  W("W");

  private String value;

  AvsResultEnum(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AvsResultEnum fromValue(String value) {
    for (AvsResultEnum b : AvsResultEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }

}
