/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.AvsResultEnum;
import com.alogram.payrisk.v1.models.CardNetworkEnum;
import com.alogram.payrisk.v1.models.CvvResultEnum;
import com.alogram.payrisk.v1.models.PaymentCardTypeEnum;
import com.alogram.payrisk.v1.models.ScaMethodEnum;
import com.alogram.payrisk.v1.models.ThreeDSData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Card
 */
@JsonPropertyOrder({
  Card.JSON_PROPERTY_TYPE,
  Card.JSON_PROPERTY_CARD_NETWORK,
  Card.JSON_PROPERTY_CARD_TYPE,
  Card.JSON_PROPERTY_BIN,
  Card.JSON_PROPERTY_ISSUER_COUNTRY,
  Card.JSON_PROPERTY_AVS_RESULT,
  Card.JSON_PROPERTY_CVV_RESULT,
  Card.JSON_PROPERTY_SCA_METHOD,
  Card.JSON_PROPERTY_THREE_D_S
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class Card {
  /**
   * Fixed to &#x60;card&#x60; for this schema.
   */
  public enum TypeEnum {
    CARD(String.valueOf("card"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_CARD_NETWORK = "cardNetwork";
  @javax.annotation.Nullable
  private CardNetworkEnum cardNetwork;

  public static final String JSON_PROPERTY_CARD_TYPE = "cardType";
  @javax.annotation.Nullable
  private PaymentCardTypeEnum cardType;

  public static final String JSON_PROPERTY_BIN = "bin";
  @javax.annotation.Nullable
  private String bin;

  public static final String JSON_PROPERTY_ISSUER_COUNTRY = "issuerCountry";
  @javax.annotation.Nullable
  private String issuerCountry;

  public static final String JSON_PROPERTY_AVS_RESULT = "avsResult";
  @javax.annotation.Nullable
  private AvsResultEnum avsResult;

  public static final String JSON_PROPERTY_CVV_RESULT = "cvvResult";
  @javax.annotation.Nullable
  private CvvResultEnum cvvResult;

  public static final String JSON_PROPERTY_SCA_METHOD = "scaMethod";
  @javax.annotation.Nullable
  private ScaMethodEnum scaMethod;

  public static final String JSON_PROPERTY_THREE_D_S = "threeDS";
  @javax.annotation.Nullable
  private ThreeDSData threeDS;

  public Card() { 
  }

  public Card type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Fixed to &#x60;card&#x60; for this schema.
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public Card cardNetwork(@javax.annotation.Nullable CardNetworkEnum cardNetwork) {
    this.cardNetwork = cardNetwork;
    return this;
  }

  /**
   * Get cardNetwork
   * @return cardNetwork
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CARD_NETWORK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CardNetworkEnum getCardNetwork() {
    return cardNetwork;
  }


  @JsonProperty(JSON_PROPERTY_CARD_NETWORK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCardNetwork(@javax.annotation.Nullable CardNetworkEnum cardNetwork) {
    this.cardNetwork = cardNetwork;
  }


  public Card cardType(@javax.annotation.Nullable PaymentCardTypeEnum cardType) {
    this.cardType = cardType;
    return this;
  }

  /**
   * Get cardType
   * @return cardType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CARD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PaymentCardTypeEnum getCardType() {
    return cardType;
  }


  @JsonProperty(JSON_PROPERTY_CARD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCardType(@javax.annotation.Nullable PaymentCardTypeEnum cardType) {
    this.cardType = cardType;
  }


  public Card bin(@javax.annotation.Nullable String bin) {
    this.bin = bin;
    return this;
  }

  /**
   * Bank Identification Number (IIN). First 6–8 digits of the PAN; do not send full PAN.
   * @return bin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBin() {
    return bin;
  }


  @JsonProperty(JSON_PROPERTY_BIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBin(@javax.annotation.Nullable String bin) {
    this.bin = bin;
  }


  public Card issuerCountry(@javax.annotation.Nullable String issuerCountry) {
    this.issuerCountry = issuerCountry;
    return this;
  }

  /**
   * ISO 3166-1 alpha-2 country code.
   * @return issuerCountry
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ISSUER_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIssuerCountry() {
    return issuerCountry;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerCountry(@javax.annotation.Nullable String issuerCountry) {
    this.issuerCountry = issuerCountry;
  }


  public Card avsResult(@javax.annotation.Nullable AvsResultEnum avsResult) {
    this.avsResult = avsResult;
    return this;
  }

  /**
   * Get avsResult
   * @return avsResult
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVS_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AvsResultEnum getAvsResult() {
    return avsResult;
  }


  @JsonProperty(JSON_PROPERTY_AVS_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvsResult(@javax.annotation.Nullable AvsResultEnum avsResult) {
    this.avsResult = avsResult;
  }


  public Card cvvResult(@javax.annotation.Nullable CvvResultEnum cvvResult) {
    this.cvvResult = cvvResult;
    return this;
  }

  /**
   * Get cvvResult
   * @return cvvResult
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CVV_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CvvResultEnum getCvvResult() {
    return cvvResult;
  }


  @JsonProperty(JSON_PROPERTY_CVV_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCvvResult(@javax.annotation.Nullable CvvResultEnum cvvResult) {
    this.cvvResult = cvvResult;
  }


  public Card scaMethod(@javax.annotation.Nullable ScaMethodEnum scaMethod) {
    this.scaMethod = scaMethod;
    return this;
  }

  /**
   * Get scaMethod
   * @return scaMethod
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCA_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ScaMethodEnum getScaMethod() {
    return scaMethod;
  }


  @JsonProperty(JSON_PROPERTY_SCA_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScaMethod(@javax.annotation.Nullable ScaMethodEnum scaMethod) {
    this.scaMethod = scaMethod;
  }


  public Card threeDS(@javax.annotation.Nullable ThreeDSData threeDS) {
    this.threeDS = threeDS;
    return this;
  }

  /**
   * Get threeDS
   * @return threeDS
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THREE_D_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ThreeDSData getThreeDS() {
    return threeDS;
  }


  @JsonProperty(JSON_PROPERTY_THREE_D_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThreeDS(@javax.annotation.Nullable ThreeDSData threeDS) {
    this.threeDS = threeDS;
  }


  /**
   * Return true if this Card object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Card card = (Card) o;
    return Objects.equals(this.type, card.type) &&
        Objects.equals(this.cardNetwork, card.cardNetwork) &&
        Objects.equals(this.cardType, card.cardType) &&
        Objects.equals(this.bin, card.bin) &&
        Objects.equals(this.issuerCountry, card.issuerCountry) &&
        Objects.equals(this.avsResult, card.avsResult) &&
        Objects.equals(this.cvvResult, card.cvvResult) &&
        Objects.equals(this.scaMethod, card.scaMethod) &&
        Objects.equals(this.threeDS, card.threeDS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, cardNetwork, cardType, bin, issuerCountry, avsResult, cvvResult, scaMethod, threeDS);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Card {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    cardNetwork: ").append(toIndentedString(cardNetwork)).append("\n");
    sb.append("    cardType: ").append(toIndentedString(cardType)).append("\n");
    sb.append("    bin: ").append(toIndentedString(bin)).append("\n");
    sb.append("    issuerCountry: ").append(toIndentedString(issuerCountry)).append("\n");
    sb.append("    avsResult: ").append(toIndentedString(avsResult)).append("\n");
    sb.append("    cvvResult: ").append(toIndentedString(cvvResult)).append("\n");
    sb.append("    scaMethod: ").append(toIndentedString(scaMethod)).append("\n");
    sb.append("    threeDS: ").append(toIndentedString(threeDS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `cardNetwork` to the URL query string
    if (getCardNetwork() != null) {
      joiner.add(String.format("%scardNetwork%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCardNetwork()))));
    }

    // add `cardType` to the URL query string
    if (getCardType() != null) {
      joiner.add(String.format("%scardType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCardType()))));
    }

    // add `bin` to the URL query string
    if (getBin() != null) {
      joiner.add(String.format("%sbin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBin()))));
    }

    // add `issuerCountry` to the URL query string
    if (getIssuerCountry() != null) {
      joiner.add(String.format("%sissuerCountry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIssuerCountry()))));
    }

    // add `avsResult` to the URL query string
    if (getAvsResult() != null) {
      joiner.add(String.format("%savsResult%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAvsResult()))));
    }

    // add `cvvResult` to the URL query string
    if (getCvvResult() != null) {
      joiner.add(String.format("%scvvResult%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCvvResult()))));
    }

    // add `scaMethod` to the URL query string
    if (getScaMethod() != null) {
      joiner.add(String.format("%sscaMethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScaMethod()))));
    }

    // add `threeDS` to the URL query string
    if (getThreeDS() != null) {
      joiner.add(getThreeDS().toUrlQueryString(prefix + "threeDS" + suffix));
    }

    return joiner.toString();
  }
}
