/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.EntityIds;
import com.alogram.payrisk.v1.models.Identity;
import com.alogram.payrisk.v1.models.Purchase;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Request for synchronous purchase risk check.
 */
@JsonPropertyOrder({
  CheckRequest.JSON_PROPERTY_EVENT_TYPE,
  CheckRequest.JSON_PROPERTY_PAYMENT_INTENT_ID,
  CheckRequest.JSON_PROPERTY_ENTITIES,
  CheckRequest.JSON_PROPERTY_PURCHASE,
  CheckRequest.JSON_PROPERTY_IDENTITY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class CheckRequest {
  /**
   * (optional) event being checked, this may expand later beyond &#39;purchase&#39;.
   */
  public enum EventTypeEnum {
    PURCHASE(String.valueOf("purchase"));

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EventTypeEnum fromValue(String value) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  @javax.annotation.Nullable
  private EventTypeEnum eventType = EventTypeEnum.PURCHASE;

  public static final String JSON_PROPERTY_PAYMENT_INTENT_ID = "paymentIntentId";
  @javax.annotation.Nullable
  private String paymentIntentId;

  public static final String JSON_PROPERTY_ENTITIES = "entities";
  @javax.annotation.Nonnull
  private EntityIds entities;

  public static final String JSON_PROPERTY_PURCHASE = "purchase";
  @javax.annotation.Nonnull
  private Purchase purchase;

  public static final String JSON_PROPERTY_IDENTITY = "identity";
  @javax.annotation.Nullable
  private Identity identity;

  public CheckRequest() { 
  }

  public CheckRequest eventType(@javax.annotation.Nullable EventTypeEnum eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * (optional) event being checked, this may expand later beyond &#39;purchase&#39;.
   * @return eventType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EventTypeEnum getEventType() {
    return eventType;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(@javax.annotation.Nullable EventTypeEnum eventType) {
    this.eventType = eventType;
  }


  public CheckRequest paymentIntentId(@javax.annotation.Nullable String paymentIntentId) {
    this.paymentIntentId = paymentIntentId;
    return this;
  }

  /**
   * Server-minted unique payment identifier.
   * @return paymentIntentId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_INTENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPaymentIntentId() {
    return paymentIntentId;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_INTENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentIntentId(@javax.annotation.Nullable String paymentIntentId) {
    this.paymentIntentId = paymentIntentId;
  }


  public CheckRequest entities(@javax.annotation.Nonnull EntityIds entities) {
    this.entities = entities;
    return this;
  }

  /**
   * Get entities
   * @return entities
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EntityIds getEntities() {
    return entities;
  }


  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntities(@javax.annotation.Nonnull EntityIds entities) {
    this.entities = entities;
  }


  public CheckRequest purchase(@javax.annotation.Nonnull Purchase purchase) {
    this.purchase = purchase;
    return this;
  }

  /**
   * Get purchase
   * @return purchase
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PURCHASE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Purchase getPurchase() {
    return purchase;
  }


  @JsonProperty(JSON_PROPERTY_PURCHASE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPurchase(@javax.annotation.Nonnull Purchase purchase) {
    this.purchase = purchase;
  }


  public CheckRequest identity(@javax.annotation.Nullable Identity identity) {
    this.identity = identity;
    return this;
  }

  /**
   * Get identity
   * @return identity
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Identity getIdentity() {
    return identity;
  }


  @JsonProperty(JSON_PROPERTY_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentity(@javax.annotation.Nullable Identity identity) {
    this.identity = identity;
  }


  /**
   * Return true if this CheckRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckRequest checkRequest = (CheckRequest) o;
    return Objects.equals(this.eventType, checkRequest.eventType) &&
        Objects.equals(this.paymentIntentId, checkRequest.paymentIntentId) &&
        Objects.equals(this.entities, checkRequest.entities) &&
        Objects.equals(this.purchase, checkRequest.purchase) &&
        Objects.equals(this.identity, checkRequest.identity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventType, paymentIntentId, entities, purchase, identity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckRequest {\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    paymentIntentId: ").append(toIndentedString(paymentIntentId)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    purchase: ").append(toIndentedString(purchase)).append("\n");
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `eventType` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format("%seventType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    // add `paymentIntentId` to the URL query string
    if (getPaymentIntentId() != null) {
      joiner.add(String.format("%spaymentIntentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentIntentId()))));
    }

    // add `entities` to the URL query string
    if (getEntities() != null) {
      joiner.add(getEntities().toUrlQueryString(prefix + "entities" + suffix));
    }

    // add `purchase` to the URL query string
    if (getPurchase() != null) {
      joiner.add(getPurchase().toUrlQueryString(prefix + "purchase" + suffix));
    }

    // add `identity` to the URL query string
    if (getIdentity() != null) {
      joiner.add(getIdentity().toUrlQueryString(prefix + "identity" + suffix));
    }

    return joiner.toString();
  }
}
