/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.FraudScore;
import com.alogram.payrisk.v1.models.ReasonDetail;
import com.alogram.payrisk.v1.models.RiskBreakdown;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * The synchronous risk decision for a purchase.
 */
@JsonPropertyOrder({
  DecisionResponse.JSON_PROPERTY_ASSESSMENT_ID,
  DecisionResponse.JSON_PROPERTY_DECISION,
  DecisionResponse.JSON_PROPERTY_DECISION_AT,
  DecisionResponse.JSON_PROPERTY_RISK_SCORE,
  DecisionResponse.JSON_PROPERTY_FRAUD_SCORE,
  DecisionResponse.JSON_PROPERTY_BREAKDOWN,
  DecisionResponse.JSON_PROPERTY_REASON_CODES,
  DecisionResponse.JSON_PROPERTY_REASONS,
  DecisionResponse.JSON_PROPERTY_ACTIONS,
  DecisionResponse.JSON_PROPERTY_PAYMENT_INTENT_ID,
  DecisionResponse.JSON_PROPERTY_POLICY_VERSION,
  DecisionResponse.JSON_PROPERTY_MODEL_VERSION,
  DecisionResponse.JSON_PROPERTY_TTL_SECONDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class DecisionResponse {
  public static final String JSON_PROPERTY_ASSESSMENT_ID = "assessmentId";
  @javax.annotation.Nonnull
  private String assessmentId;

  /**
   * Gets or Sets decision
   */
  public enum DecisionEnum {
    APPROVE(String.valueOf("approve")),
    
    REVIEW(String.valueOf("review")),
    
    DECLINE(String.valueOf("decline")),
    
    STEP_UP(String.valueOf("step_up"));

    private String value;

    DecisionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DecisionEnum fromValue(String value) {
      for (DecisionEnum b : DecisionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DECISION = "decision";
  @javax.annotation.Nonnull
  private DecisionEnum decision;

  public static final String JSON_PROPERTY_DECISION_AT = "decisionAt";
  @javax.annotation.Nonnull
  private String decisionAt;

  public static final String JSON_PROPERTY_RISK_SCORE = "riskScore";
  @javax.annotation.Nonnull
  private Float riskScore;

  public static final String JSON_PROPERTY_FRAUD_SCORE = "fraudScore";
  @javax.annotation.Nullable
  private FraudScore fraudScore;

  public static final String JSON_PROPERTY_BREAKDOWN = "breakdown";
  @javax.annotation.Nullable
  private RiskBreakdown breakdown;

  public static final String JSON_PROPERTY_REASON_CODES = "reasonCodes";
  @javax.annotation.Nullable
  private List<String> reasonCodes = new ArrayList<>();

  public static final String JSON_PROPERTY_REASONS = "reasons";
  @javax.annotation.Nullable
  private List<ReasonDetail> reasons = new ArrayList<>();

  /**
   * Action to be taken based on the decision. &#39;step_up&#39; for Strong Customer Authentication, &#39;throttle&#39; for rate limiting, &#39;lock_account&#39; for account suspension, &#39;decline&#39; for transaction rejection, &#39;queue_review&#39; for manual review. 
   */
  public enum ActionsEnum {
    STEP_UP(String.valueOf("step_up")),
    
    THROTTLE(String.valueOf("throttle")),
    
    LOCK_ACCOUNT(String.valueOf("lock_account")),
    
    DECLINE(String.valueOf("decline")),
    
    QUEUE_REVIEW(String.valueOf("queue_review"));

    private String value;

    ActionsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionsEnum fromValue(String value) {
      for (ActionsEnum b : ActionsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTIONS = "actions";
  @javax.annotation.Nullable
  private List<ActionsEnum> actions = new ArrayList<>();

  public static final String JSON_PROPERTY_PAYMENT_INTENT_ID = "paymentIntentId";
  @javax.annotation.Nullable
  private String paymentIntentId;

  public static final String JSON_PROPERTY_POLICY_VERSION = "policyVersion";
  @javax.annotation.Nullable
  private String policyVersion;

  public static final String JSON_PROPERTY_MODEL_VERSION = "modelVersion";
  @javax.annotation.Nullable
  private String modelVersion;

  public static final String JSON_PROPERTY_TTL_SECONDS = "ttlSeconds";
  @javax.annotation.Nullable
  private Integer ttlSeconds;

  public DecisionResponse() { 
  }

  public DecisionResponse assessmentId(@javax.annotation.Nonnull String assessmentId) {
    this.assessmentId = assessmentId;
    return this;
  }

  /**
   * Universal decision identifier. For purchases, equals paymentIntentId.
   * @return assessmentId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSESSMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAssessmentId() {
    return assessmentId;
  }


  @JsonProperty(JSON_PROPERTY_ASSESSMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssessmentId(@javax.annotation.Nonnull String assessmentId) {
    this.assessmentId = assessmentId;
  }


  public DecisionResponse decision(@javax.annotation.Nonnull DecisionEnum decision) {
    this.decision = decision;
    return this;
  }

  /**
   * Get decision
   * @return decision
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DECISION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DecisionEnum getDecision() {
    return decision;
  }


  @JsonProperty(JSON_PROPERTY_DECISION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDecision(@javax.annotation.Nonnull DecisionEnum decision) {
    this.decision = decision;
  }


  public DecisionResponse decisionAt(@javax.annotation.Nonnull String decisionAt) {
    this.decisionAt = decisionAt;
    return this;
  }

  /**
   * RFC 3339 timestamp with timezone.
   * @return decisionAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DECISION_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDecisionAt() {
    return decisionAt;
  }


  @JsonProperty(JSON_PROPERTY_DECISION_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDecisionAt(@javax.annotation.Nonnull String decisionAt) {
    this.decisionAt = decisionAt;
  }


  public DecisionResponse riskScore(@javax.annotation.Nonnull Float riskScore) {
    this.riskScore = riskScore;
    return this;
  }

  /**
   * Get riskScore
   * minimum: 0.0
   * maximum: 1.0
   * @return riskScore
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RISK_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Float getRiskScore() {
    return riskScore;
  }


  @JsonProperty(JSON_PROPERTY_RISK_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRiskScore(@javax.annotation.Nonnull Float riskScore) {
    this.riskScore = riskScore;
  }


  public DecisionResponse fraudScore(@javax.annotation.Nullable FraudScore fraudScore) {
    this.fraudScore = fraudScore;
    return this;
  }

  /**
   * Get fraudScore
   * @return fraudScore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FRAUD_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FraudScore getFraudScore() {
    return fraudScore;
  }


  @JsonProperty(JSON_PROPERTY_FRAUD_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFraudScore(@javax.annotation.Nullable FraudScore fraudScore) {
    this.fraudScore = fraudScore;
  }


  public DecisionResponse breakdown(@javax.annotation.Nullable RiskBreakdown breakdown) {
    this.breakdown = breakdown;
    return this;
  }

  /**
   * Get breakdown
   * @return breakdown
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BREAKDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RiskBreakdown getBreakdown() {
    return breakdown;
  }


  @JsonProperty(JSON_PROPERTY_BREAKDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBreakdown(@javax.annotation.Nullable RiskBreakdown breakdown) {
    this.breakdown = breakdown;
  }


  public DecisionResponse reasonCodes(@javax.annotation.Nullable List<String> reasonCodes) {
    this.reasonCodes = reasonCodes;
    return this;
  }

  public DecisionResponse addReasonCodesItem(String reasonCodesItem) {
    if (this.reasonCodes == null) {
      this.reasonCodes = new ArrayList<>();
    }
    this.reasonCodes.add(reasonCodesItem);
    return this;
  }

  /**
   * Technical reason codes for the decision.
   * @return reasonCodes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REASON_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getReasonCodes() {
    return reasonCodes;
  }


  @JsonProperty(JSON_PROPERTY_REASON_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReasonCodes(@javax.annotation.Nullable List<String> reasonCodes) {
    this.reasonCodes = reasonCodes;
  }


  public DecisionResponse reasons(@javax.annotation.Nullable List<ReasonDetail> reasons) {
    this.reasons = reasons;
    return this;
  }

  public DecisionResponse addReasonsItem(ReasonDetail reasonsItem) {
    if (this.reasons == null) {
      this.reasons = new ArrayList<>();
    }
    this.reasons.add(reasonsItem);
    return this;
  }

  /**
   * Structured reason details for the decision.
   * @return reasons
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REASONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ReasonDetail> getReasons() {
    return reasons;
  }


  @JsonProperty(JSON_PROPERTY_REASONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReasons(@javax.annotation.Nullable List<ReasonDetail> reasons) {
    this.reasons = reasons;
  }


  public DecisionResponse actions(@javax.annotation.Nullable List<ActionsEnum> actions) {
    this.actions = actions;
    return this;
  }

  public DecisionResponse addActionsItem(ActionsEnum actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<>();
    }
    this.actions.add(actionsItem);
    return this;
  }

  /**
   * Get actions
   * @return actions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ActionsEnum> getActions() {
    return actions;
  }


  @JsonProperty(JSON_PROPERTY_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActions(@javax.annotation.Nullable List<ActionsEnum> actions) {
    this.actions = actions;
  }


  public DecisionResponse paymentIntentId(@javax.annotation.Nullable String paymentIntentId) {
    this.paymentIntentId = paymentIntentId;
    return this;
  }

  /**
   * Server-minted unique payment identifier.
   * @return paymentIntentId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_INTENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPaymentIntentId() {
    return paymentIntentId;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_INTENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentIntentId(@javax.annotation.Nullable String paymentIntentId) {
    this.paymentIntentId = paymentIntentId;
  }


  public DecisionResponse policyVersion(@javax.annotation.Nullable String policyVersion) {
    this.policyVersion = policyVersion;
    return this;
  }

  /**
   * The version of the policy that generated the decision.
   * @return policyVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPolicyVersion() {
    return policyVersion;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyVersion(@javax.annotation.Nullable String policyVersion) {
    this.policyVersion = policyVersion;
  }


  public DecisionResponse modelVersion(@javax.annotation.Nullable String modelVersion) {
    this.modelVersion = modelVersion;
    return this;
  }

  /**
   * The version of the model that generated the decision.
   * @return modelVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getModelVersion() {
    return modelVersion;
  }


  @JsonProperty(JSON_PROPERTY_MODEL_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModelVersion(@javax.annotation.Nullable String modelVersion) {
    this.modelVersion = modelVersion;
  }


  public DecisionResponse ttlSeconds(@javax.annotation.Nullable Integer ttlSeconds) {
    this.ttlSeconds = ttlSeconds;
    return this;
  }

  /**
   * Time to live for the decision in seconds.
   * minimum: 0
   * @return ttlSeconds
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TTL_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTtlSeconds() {
    return ttlSeconds;
  }


  @JsonProperty(JSON_PROPERTY_TTL_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTtlSeconds(@javax.annotation.Nullable Integer ttlSeconds) {
    this.ttlSeconds = ttlSeconds;
  }


  /**
   * Return true if this DecisionResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DecisionResponse decisionResponse = (DecisionResponse) o;
    return Objects.equals(this.assessmentId, decisionResponse.assessmentId) &&
        Objects.equals(this.decision, decisionResponse.decision) &&
        Objects.equals(this.decisionAt, decisionResponse.decisionAt) &&
        Objects.equals(this.riskScore, decisionResponse.riskScore) &&
        Objects.equals(this.fraudScore, decisionResponse.fraudScore) &&
        Objects.equals(this.breakdown, decisionResponse.breakdown) &&
        Objects.equals(this.reasonCodes, decisionResponse.reasonCodes) &&
        Objects.equals(this.reasons, decisionResponse.reasons) &&
        Objects.equals(this.actions, decisionResponse.actions) &&
        Objects.equals(this.paymentIntentId, decisionResponse.paymentIntentId) &&
        Objects.equals(this.policyVersion, decisionResponse.policyVersion) &&
        Objects.equals(this.modelVersion, decisionResponse.modelVersion) &&
        Objects.equals(this.ttlSeconds, decisionResponse.ttlSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assessmentId, decision, decisionAt, riskScore, fraudScore, breakdown, reasonCodes, reasons, actions, paymentIntentId, policyVersion, modelVersion, ttlSeconds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DecisionResponse {\n");
    sb.append("    assessmentId: ").append(toIndentedString(assessmentId)).append("\n");
    sb.append("    decision: ").append(toIndentedString(decision)).append("\n");
    sb.append("    decisionAt: ").append(toIndentedString(decisionAt)).append("\n");
    sb.append("    riskScore: ").append(toIndentedString(riskScore)).append("\n");
    sb.append("    fraudScore: ").append(toIndentedString(fraudScore)).append("\n");
    sb.append("    breakdown: ").append(toIndentedString(breakdown)).append("\n");
    sb.append("    reasonCodes: ").append(toIndentedString(reasonCodes)).append("\n");
    sb.append("    reasons: ").append(toIndentedString(reasons)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    paymentIntentId: ").append(toIndentedString(paymentIntentId)).append("\n");
    sb.append("    policyVersion: ").append(toIndentedString(policyVersion)).append("\n");
    sb.append("    modelVersion: ").append(toIndentedString(modelVersion)).append("\n");
    sb.append("    ttlSeconds: ").append(toIndentedString(ttlSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `assessmentId` to the URL query string
    if (getAssessmentId() != null) {
      joiner.add(String.format("%sassessmentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAssessmentId()))));
    }

    // add `decision` to the URL query string
    if (getDecision() != null) {
      joiner.add(String.format("%sdecision%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDecision()))));
    }

    // add `decisionAt` to the URL query string
    if (getDecisionAt() != null) {
      joiner.add(String.format("%sdecisionAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDecisionAt()))));
    }

    // add `riskScore` to the URL query string
    if (getRiskScore() != null) {
      joiner.add(String.format("%sriskScore%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRiskScore()))));
    }

    // add `fraudScore` to the URL query string
    if (getFraudScore() != null) {
      joiner.add(getFraudScore().toUrlQueryString(prefix + "fraudScore" + suffix));
    }

    // add `breakdown` to the URL query string
    if (getBreakdown() != null) {
      joiner.add(getBreakdown().toUrlQueryString(prefix + "breakdown" + suffix));
    }

    // add `reasonCodes` to the URL query string
    if (getReasonCodes() != null) {
      for (int i = 0; i < getReasonCodes().size(); i++) {
        joiner.add(String.format("%sreasonCodes%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getReasonCodes().get(i)))));
      }
    }

    // add `reasons` to the URL query string
    if (getReasons() != null) {
      for (int i = 0; i < getReasons().size(); i++) {
        if (getReasons().get(i) != null) {
          joiner.add(getReasons().get(i).toUrlQueryString(String.format("%sreasons%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `actions` to the URL query string
    if (getActions() != null) {
      for (int i = 0; i < getActions().size(); i++) {
        joiner.add(String.format("%sactions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getActions().get(i)))));
      }
    }

    // add `paymentIntentId` to the URL query string
    if (getPaymentIntentId() != null) {
      joiner.add(String.format("%spaymentIntentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentIntentId()))));
    }

    // add `policyVersion` to the URL query string
    if (getPolicyVersion() != null) {
      joiner.add(String.format("%spolicyVersion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPolicyVersion()))));
    }

    // add `modelVersion` to the URL query string
    if (getModelVersion() != null) {
      joiner.add(String.format("%smodelVersion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModelVersion()))));
    }

    // add `ttlSeconds` to the URL query string
    if (getTtlSeconds() != null) {
      joiner.add(String.format("%sttlSeconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTtlSeconds()))));
    }

    return joiner.toString();
  }
}
