/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Canonical entity identifiers (tenant/client/user/device/session). Do not send raw PII. Hash emails/phones/addresses as sha256 and prefix with &#39;sha256_&#39;. Tiered support:   - tenantId is the top-level SaaS customer (required for all flows).   - clientId is the tenant’s downstream business customer (e.g. merchant/partner) and MAY be omitted for     processor / bank / PSP-style integrations.   - endCustomerId is the tenant/client’s consumer or business account (cardholder, shopper, etc.) and     MAY be omitted for purely device- or instrument-level checks. 
 */
@JsonPropertyOrder({
  EntityIds.JSON_PROPERTY_TENANT_ID,
  EntityIds.JSON_PROPERTY_CLIENT_ID,
  EntityIds.JSON_PROPERTY_END_CUSTOMER_ID,
  EntityIds.JSON_PROPERTY_MEMBER_ID,
  EntityIds.JSON_PROPERTY_PAYMENT_INSTRUMENT_ID,
  EntityIds.JSON_PROPERTY_DEVICE_ID,
  EntityIds.JSON_PROPERTY_SESSION_ID,
  EntityIds.JSON_PROPERTY_EMAIL_HASH,
  EntityIds.JSON_PROPERTY_EMAIL_DOMAIN_HASH,
  EntityIds.JSON_PROPERTY_PHONE_HASH,
  EntityIds.JSON_PROPERTY_SHIPPING_ADDRESS_HASH,
  EntityIds.JSON_PROPERTY_BILLING_ADDRESS_HASH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class EntityIds {
  public static final String JSON_PROPERTY_TENANT_ID = "tenantId";
  @javax.annotation.Nullable
  private String tenantId;

  public static final String JSON_PROPERTY_CLIENT_ID = "clientId";
  @javax.annotation.Nullable
  private String clientId;

  public static final String JSON_PROPERTY_END_CUSTOMER_ID = "endCustomerId";
  @javax.annotation.Nullable
  private String endCustomerId;

  public static final String JSON_PROPERTY_MEMBER_ID = "memberId";
  @javax.annotation.Nullable
  private String memberId;

  public static final String JSON_PROPERTY_PAYMENT_INSTRUMENT_ID = "paymentInstrumentId";
  @javax.annotation.Nullable
  private String paymentInstrumentId;

  public static final String JSON_PROPERTY_DEVICE_ID = "deviceId";
  @javax.annotation.Nullable
  private String deviceId;

  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  @javax.annotation.Nullable
  private String sessionId;

  public static final String JSON_PROPERTY_EMAIL_HASH = "emailHash";
  @javax.annotation.Nullable
  private String emailHash;

  public static final String JSON_PROPERTY_EMAIL_DOMAIN_HASH = "emailDomainHash";
  @javax.annotation.Nullable
  private String emailDomainHash;

  public static final String JSON_PROPERTY_PHONE_HASH = "phoneHash";
  @javax.annotation.Nullable
  private String phoneHash;

  public static final String JSON_PROPERTY_SHIPPING_ADDRESS_HASH = "shippingAddressHash";
  @javax.annotation.Nullable
  private String shippingAddressHash;

  public static final String JSON_PROPERTY_BILLING_ADDRESS_HASH = "billingAddressHash";
  @javax.annotation.Nullable
  private String billingAddressHash;

  public EntityIds() { 
  }

  public EntityIds tenantId(@javax.annotation.Nullable String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Canonical ID for the paying organization (Tenant). Opaque, immutable, lowercase.  Must start with \&quot;tid_\&quot;. Do not use domains or emails here. For a tenant&#39;s domain,  use a separate field (e.g., tenantDomain). 
   * @return tenantId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTenantId() {
    return tenantId;
  }


  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTenantId(@javax.annotation.Nullable String tenantId) {
    this.tenantId = tenantId;
  }


  public EntityIds clientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Canonical ID for the Tenant’s business customer (e.g., merchant/partner).  Opaque, immutable, lowercase. Must start with &#39;cid_&#39;. 
   * @return clientId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getClientId() {
    return clientId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
  }


  public EntityIds endCustomerId(@javax.annotation.Nullable String endCustomerId) {
    this.endCustomerId = endCustomerId;
    return this;
  }

  /**
   * Canonical ID for the client’s end user / consumer (account holder).  Opaque, immutable, lowercase. Must start with \&quot;ecid_\&quot;.  Do not put PII (like emails or phone numbers) in this field. 
   * @return endCustomerId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEndCustomerId() {
    return endCustomerId;
  }


  @JsonProperty(JSON_PROPERTY_END_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndCustomerId(@javax.annotation.Nullable String endCustomerId) {
    this.endCustomerId = endCustomerId;
  }


  public EntityIds memberId(@javax.annotation.Nullable String memberId) {
    this.memberId = memberId;
    return this;
  }

  /**
   * Canonical ID for a Tenant member/operator (employee/contractor) using the platform.  Opaque, immutable, lowercase. Must start with &#39;mid_&#39;. 
   * @return memberId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEMBER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMemberId() {
    return memberId;
  }


  @JsonProperty(JSON_PROPERTY_MEMBER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemberId(@javax.annotation.Nullable String memberId) {
    this.memberId = memberId;
  }


  public EntityIds paymentInstrumentId(@javax.annotation.Nullable String paymentInstrumentId) {
    this.paymentInstrumentId = paymentInstrumentId;
    return this;
  }

  /**
   * Tokenized instrument ID (non-PCI).
   * @return paymentInstrumentId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_INSTRUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPaymentInstrumentId() {
    return paymentInstrumentId;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_INSTRUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentInstrumentId(@javax.annotation.Nullable String paymentInstrumentId) {
    this.paymentInstrumentId = paymentInstrumentId;
  }


  public EntityIds deviceId(@javax.annotation.Nullable String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * Server-issued stable device token (device-level identifier). Should persist across sessions and logins on the same browser/device. 
   * @return deviceId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDeviceId() {
    return deviceId;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceId(@javax.annotation.Nullable String deviceId) {
    this.deviceId = deviceId;
  }


  public EntityIds sessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

  /**
   * Application/user session identifier (login or checkout session). Typically rotates more frequently than deviceId and may be tied to authentication. 
   * @return sessionId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSessionId() {
    return sessionId;
  }


  @JsonProperty(JSON_PROPERTY_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
  }


  public EntityIds emailHash(@javax.annotation.Nullable String emailHash) {
    this.emailHash = emailHash;
    return this;
  }

  /**
   * Normalized+lowercased email hash (e.g., sha256).
   * @return emailHash
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmailHash() {
    return emailHash;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailHash(@javax.annotation.Nullable String emailHash) {
    this.emailHash = emailHash;
  }


  public EntityIds emailDomainHash(@javax.annotation.Nullable String emailDomainHash) {
    this.emailDomainHash = emailDomainHash;
    return this;
  }

  /**
   * Normalized+lowercased email *domain* hash (e.g., sha256).
   * @return emailDomainHash
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL_DOMAIN_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmailDomainHash() {
    return emailDomainHash;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_DOMAIN_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailDomainHash(@javax.annotation.Nullable String emailDomainHash) {
    this.emailDomainHash = emailDomainHash;
  }


  public EntityIds phoneHash(@javax.annotation.Nullable String phoneHash) {
    this.phoneHash = phoneHash;
    return this;
  }

  /**
   * Normalized+lowercased phone hash (e.g., sha256).
   * @return phoneHash
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPhoneHash() {
    return phoneHash;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneHash(@javax.annotation.Nullable String phoneHash) {
    this.phoneHash = phoneHash;
  }


  public EntityIds shippingAddressHash(@javax.annotation.Nullable String shippingAddressHash) {
    this.shippingAddressHash = shippingAddressHash;
    return this;
  }

  /**
   * Normalized+lowercased shipping address hash (e.g., sha256).
   * @return shippingAddressHash
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_ADDRESS_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getShippingAddressHash() {
    return shippingAddressHash;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_ADDRESS_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingAddressHash(@javax.annotation.Nullable String shippingAddressHash) {
    this.shippingAddressHash = shippingAddressHash;
  }


  public EntityIds billingAddressHash(@javax.annotation.Nullable String billingAddressHash) {
    this.billingAddressHash = billingAddressHash;
    return this;
  }

  /**
   * Normalized+lowercased billing address hash (e.g., sha256).
   * @return billingAddressHash
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BILLING_ADDRESS_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBillingAddressHash() {
    return billingAddressHash;
  }


  @JsonProperty(JSON_PROPERTY_BILLING_ADDRESS_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBillingAddressHash(@javax.annotation.Nullable String billingAddressHash) {
    this.billingAddressHash = billingAddressHash;
  }


  /**
   * Return true if this EntityIds object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityIds entityIds = (EntityIds) o;
    return Objects.equals(this.tenantId, entityIds.tenantId) &&
        Objects.equals(this.clientId, entityIds.clientId) &&
        Objects.equals(this.endCustomerId, entityIds.endCustomerId) &&
        Objects.equals(this.memberId, entityIds.memberId) &&
        Objects.equals(this.paymentInstrumentId, entityIds.paymentInstrumentId) &&
        Objects.equals(this.deviceId, entityIds.deviceId) &&
        Objects.equals(this.sessionId, entityIds.sessionId) &&
        Objects.equals(this.emailHash, entityIds.emailHash) &&
        Objects.equals(this.emailDomainHash, entityIds.emailDomainHash) &&
        Objects.equals(this.phoneHash, entityIds.phoneHash) &&
        Objects.equals(this.shippingAddressHash, entityIds.shippingAddressHash) &&
        Objects.equals(this.billingAddressHash, entityIds.billingAddressHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, clientId, endCustomerId, memberId, paymentInstrumentId, deviceId, sessionId, emailHash, emailDomainHash, phoneHash, shippingAddressHash, billingAddressHash);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityIds {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    endCustomerId: ").append(toIndentedString(endCustomerId)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    paymentInstrumentId: ").append(toIndentedString(paymentInstrumentId)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    emailHash: ").append(toIndentedString(emailHash)).append("\n");
    sb.append("    emailDomainHash: ").append(toIndentedString(emailDomainHash)).append("\n");
    sb.append("    phoneHash: ").append(toIndentedString(phoneHash)).append("\n");
    sb.append("    shippingAddressHash: ").append(toIndentedString(shippingAddressHash)).append("\n");
    sb.append("    billingAddressHash: ").append(toIndentedString(billingAddressHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `tenantId` to the URL query string
    if (getTenantId() != null) {
      joiner.add(String.format("%stenantId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTenantId()))));
    }

    // add `clientId` to the URL query string
    if (getClientId() != null) {
      joiner.add(String.format("%sclientId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClientId()))));
    }

    // add `endCustomerId` to the URL query string
    if (getEndCustomerId() != null) {
      joiner.add(String.format("%sendCustomerId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndCustomerId()))));
    }

    // add `memberId` to the URL query string
    if (getMemberId() != null) {
      joiner.add(String.format("%smemberId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMemberId()))));
    }

    // add `paymentInstrumentId` to the URL query string
    if (getPaymentInstrumentId() != null) {
      joiner.add(String.format("%spaymentInstrumentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentInstrumentId()))));
    }

    // add `deviceId` to the URL query string
    if (getDeviceId() != null) {
      joiner.add(String.format("%sdeviceId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeviceId()))));
    }

    // add `sessionId` to the URL query string
    if (getSessionId() != null) {
      joiner.add(String.format("%ssessionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSessionId()))));
    }

    // add `emailHash` to the URL query string
    if (getEmailHash() != null) {
      joiner.add(String.format("%semailHash%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmailHash()))));
    }

    // add `emailDomainHash` to the URL query string
    if (getEmailDomainHash() != null) {
      joiner.add(String.format("%semailDomainHash%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmailDomainHash()))));
    }

    // add `phoneHash` to the URL query string
    if (getPhoneHash() != null) {
      joiner.add(String.format("%sphoneHash%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhoneHash()))));
    }

    // add `shippingAddressHash` to the URL query string
    if (getShippingAddressHash() != null) {
      joiner.add(String.format("%sshippingAddressHash%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShippingAddressHash()))));
    }

    // add `billingAddressHash` to the URL query string
    if (getBillingAddressHash() != null) {
      joiner.add(String.format("%sbillingAddressHash%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBillingAddressHash()))));
    }

    return joiner.toString();
  }
}
