/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.DeviceInfo;
import com.alogram.payrisk.v1.models.InteractionTypeEnum;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * The application-layer Interaction object.
 */
@JsonPropertyOrder({
  Interaction.JSON_PROPERTY_LOCATION_ID,
  Interaction.JSON_PROPERTY_DEVICE_INFO,
  Interaction.JSON_PROPERTY_TIMESTAMP,
  Interaction.JSON_PROPERTY_INTERACTION_TYPE,
  Interaction.JSON_PROPERTY_METADATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class Interaction {
  public static final String JSON_PROPERTY_LOCATION_ID = "locationId";
  @javax.annotation.Nullable
  private String locationId;

  public static final String JSON_PROPERTY_DEVICE_INFO = "deviceInfo";
  @javax.annotation.Nullable
  private DeviceInfo deviceInfo;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private String timestamp;

  public static final String JSON_PROPERTY_INTERACTION_TYPE = "interactionType";
  @javax.annotation.Nonnull
  private InteractionTypeEnum interactionType;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private String metadata;

  public Interaction() { 
  }

  public Interaction locationId(@javax.annotation.Nullable String locationId) {
    this.locationId = locationId;
    return this;
  }

  /**
   * Unique identifier for the location where the transaction occurred.
   * @return locationId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLocationId() {
    return locationId;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocationId(@javax.annotation.Nullable String locationId) {
    this.locationId = locationId;
  }


  public Interaction deviceInfo(@javax.annotation.Nullable DeviceInfo deviceInfo) {
    this.deviceInfo = deviceInfo;
    return this;
  }

  /**
   * Get deviceInfo
   * @return deviceInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DeviceInfo getDeviceInfo() {
    return deviceInfo;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceInfo(@javax.annotation.Nullable DeviceInfo deviceInfo) {
    this.deviceInfo = deviceInfo;
  }


  public Interaction timestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * RFC 3339 timestamp with timezone.
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
  }


  public Interaction interactionType(@javax.annotation.Nonnull InteractionTypeEnum interactionType) {
    this.interactionType = interactionType;
    return this;
  }

  /**
   * Get interactionType
   * @return interactionType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INTERACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public InteractionTypeEnum getInteractionType() {
    return interactionType;
  }


  @JsonProperty(JSON_PROPERTY_INTERACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInteractionType(@javax.annotation.Nonnull InteractionTypeEnum interactionType) {
    this.interactionType = interactionType;
  }


  public Interaction metadata(@javax.annotation.Nullable String metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable String metadata) {
    this.metadata = metadata;
  }


  /**
   * Return true if this Interaction object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Interaction interaction = (Interaction) o;
    return Objects.equals(this.locationId, interaction.locationId) &&
        Objects.equals(this.deviceInfo, interaction.deviceInfo) &&
        Objects.equals(this.timestamp, interaction.timestamp) &&
        Objects.equals(this.interactionType, interaction.interactionType) &&
        Objects.equals(this.metadata, interaction.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationId, deviceInfo, timestamp, interactionType, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Interaction {\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    deviceInfo: ").append(toIndentedString(deviceInfo)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    interactionType: ").append(toIndentedString(interactionType)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `locationId` to the URL query string
    if (getLocationId() != null) {
      joiner.add(String.format("%slocationId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLocationId()))));
    }

    // add `deviceInfo` to the URL query string
    if (getDeviceInfo() != null) {
      joiner.add(getDeviceInfo().toUrlQueryString(prefix + "deviceInfo" + suffix));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format("%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `interactionType` to the URL query string
    if (getInteractionType() != null) {
      joiner.add(String.format("%sinteractionType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInteractionType()))));
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      joiner.add(String.format("%smetadata%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetadata()))));
    }

    return joiner.toString();
  }
}
