/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Integrity
 */
@JsonPropertyOrder({
  Integrity.JSON_PROPERTY_IS_PROXY_VPN_TOR,
  Integrity.JSON_PROPERTY_IS_HOSTING_PROVIDER,
  Integrity.JSON_PROPERTY_IS_HEADLESS,
  Integrity.JSON_PROPERTY_IS_AUTOMATION,
  Integrity.JSON_PROPERTY_IS_EMULATOR,
  Integrity.JSON_PROPERTY_IS_ROOTED_JAILBROKEN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class Integrity {
  public static final String JSON_PROPERTY_IS_PROXY_VPN_TOR = "isProxyVpnTor";
  @javax.annotation.Nullable
  private Boolean isProxyVpnTor;

  public static final String JSON_PROPERTY_IS_HOSTING_PROVIDER = "isHostingProvider";
  @javax.annotation.Nullable
  private Boolean isHostingProvider;

  public static final String JSON_PROPERTY_IS_HEADLESS = "isHeadless";
  @javax.annotation.Nullable
  private Boolean isHeadless;

  public static final String JSON_PROPERTY_IS_AUTOMATION = "isAutomation";
  @javax.annotation.Nullable
  private Boolean isAutomation;

  public static final String JSON_PROPERTY_IS_EMULATOR = "isEmulator";
  @javax.annotation.Nullable
  private Boolean isEmulator;

  public static final String JSON_PROPERTY_IS_ROOTED_JAILBROKEN = "isRootedJailbroken";
  @javax.annotation.Nullable
  private Boolean isRootedJailbroken;

  public Integrity() { 
  }

  public Integrity isProxyVpnTor(@javax.annotation.Nullable Boolean isProxyVpnTor) {
    this.isProxyVpnTor = isProxyVpnTor;
    return this;
  }

  /**
   * Indicates whether the IP address is associated with a proxy, VPN, or Tor exit node. 
   * @return isProxyVpnTor
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_PROXY_VPN_TOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsProxyVpnTor() {
    return isProxyVpnTor;
  }


  @JsonProperty(JSON_PROPERTY_IS_PROXY_VPN_TOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsProxyVpnTor(@javax.annotation.Nullable Boolean isProxyVpnTor) {
    this.isProxyVpnTor = isProxyVpnTor;
  }


  public Integrity isHostingProvider(@javax.annotation.Nullable Boolean isHostingProvider) {
    this.isHostingProvider = isHostingProvider;
    return this;
  }

  /**
   * Indicates whether the IP address belongs to a hosting provider (e.g., data center, cloud provider). 
   * @return isHostingProvider
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_HOSTING_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsHostingProvider() {
    return isHostingProvider;
  }


  @JsonProperty(JSON_PROPERTY_IS_HOSTING_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsHostingProvider(@javax.annotation.Nullable Boolean isHostingProvider) {
    this.isHostingProvider = isHostingProvider;
  }


  public Integrity isHeadless(@javax.annotation.Nullable Boolean isHeadless) {
    this.isHeadless = isHeadless;
    return this;
  }

  /**
   * Indicates whether the browser is running in headless mode (e.g., automated testing, scraping). 
   * @return isHeadless
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_HEADLESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsHeadless() {
    return isHeadless;
  }


  @JsonProperty(JSON_PROPERTY_IS_HEADLESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsHeadless(@javax.annotation.Nullable Boolean isHeadless) {
    this.isHeadless = isHeadless;
  }


  public Integrity isAutomation(@javax.annotation.Nullable Boolean isAutomation) {
    this.isAutomation = isAutomation;
    return this;
  }

  /**
   * Indicates whether the request originated from an automated script or bot. 
   * @return isAutomation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_AUTOMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsAutomation() {
    return isAutomation;
  }


  @JsonProperty(JSON_PROPERTY_IS_AUTOMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsAutomation(@javax.annotation.Nullable Boolean isAutomation) {
    this.isAutomation = isAutomation;
  }


  public Integrity isEmulator(@javax.annotation.Nullable Boolean isEmulator) {
    this.isEmulator = isEmulator;
    return this;
  }

  /**
   * Indicates whether the request originated from an emulator (e.g., Android Emulator, iOS Simulator). 
   * @return isEmulator
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_EMULATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsEmulator() {
    return isEmulator;
  }


  @JsonProperty(JSON_PROPERTY_IS_EMULATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsEmulator(@javax.annotation.Nullable Boolean isEmulator) {
    this.isEmulator = isEmulator;
  }


  public Integrity isRootedJailbroken(@javax.annotation.Nullable Boolean isRootedJailbroken) {
    this.isRootedJailbroken = isRootedJailbroken;
    return this;
  }

  /**
   * Indicates whether the device is rooted (Android) or jailbroken (iOS). 
   * @return isRootedJailbroken
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_ROOTED_JAILBROKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsRootedJailbroken() {
    return isRootedJailbroken;
  }


  @JsonProperty(JSON_PROPERTY_IS_ROOTED_JAILBROKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsRootedJailbroken(@javax.annotation.Nullable Boolean isRootedJailbroken) {
    this.isRootedJailbroken = isRootedJailbroken;
  }


  /**
   * Return true if this Integrity object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Integrity integrity = (Integrity) o;
    return Objects.equals(this.isProxyVpnTor, integrity.isProxyVpnTor) &&
        Objects.equals(this.isHostingProvider, integrity.isHostingProvider) &&
        Objects.equals(this.isHeadless, integrity.isHeadless) &&
        Objects.equals(this.isAutomation, integrity.isAutomation) &&
        Objects.equals(this.isEmulator, integrity.isEmulator) &&
        Objects.equals(this.isRootedJailbroken, integrity.isRootedJailbroken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isProxyVpnTor, isHostingProvider, isHeadless, isAutomation, isEmulator, isRootedJailbroken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Integrity {\n");
    sb.append("    isProxyVpnTor: ").append(toIndentedString(isProxyVpnTor)).append("\n");
    sb.append("    isHostingProvider: ").append(toIndentedString(isHostingProvider)).append("\n");
    sb.append("    isHeadless: ").append(toIndentedString(isHeadless)).append("\n");
    sb.append("    isAutomation: ").append(toIndentedString(isAutomation)).append("\n");
    sb.append("    isEmulator: ").append(toIndentedString(isEmulator)).append("\n");
    sb.append("    isRootedJailbroken: ").append(toIndentedString(isRootedJailbroken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `isProxyVpnTor` to the URL query string
    if (getIsProxyVpnTor() != null) {
      joiner.add(String.format("%sisProxyVpnTor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsProxyVpnTor()))));
    }

    // add `isHostingProvider` to the URL query string
    if (getIsHostingProvider() != null) {
      joiner.add(String.format("%sisHostingProvider%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsHostingProvider()))));
    }

    // add `isHeadless` to the URL query string
    if (getIsHeadless() != null) {
      joiner.add(String.format("%sisHeadless%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsHeadless()))));
    }

    // add `isAutomation` to the URL query string
    if (getIsAutomation() != null) {
      joiner.add(String.format("%sisAutomation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsAutomation()))));
    }

    // add `isEmulator` to the URL query string
    if (getIsEmulator() != null) {
      joiner.add(String.format("%sisEmulator%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsEmulator()))));
    }

    // add `isRootedJailbroken` to the URL query string
    if (getIsRootedJailbroken() != null) {
      joiner.add(String.format("%sisRootedJailbroken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsRootedJailbroken()))));
    }

    return joiner.toString();
  }
}
