/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * IpInfo
 */
@JsonPropertyOrder({
  IpInfo.JSON_PROPERTY_IP_ADDRESS,
  IpInfo.JSON_PROPERTY_IPV6,
  IpInfo.JSON_PROPERTY_IP_VERSION,
  IpInfo.JSON_PROPERTY_IP_PREFIX,
  IpInfo.JSON_PROPERTY_ASN,
  IpInfo.JSON_PROPERTY_ORG,
  IpInfo.JSON_PROPERTY_COMPANY,
  IpInfo.JSON_PROPERTY_COUNTRY,
  IpInfo.JSON_PROPERTY_REGION,
  IpInfo.JSON_PROPERTY_CITY,
  IpInfo.JSON_PROPERTY_POSTAL_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class IpInfo {
  public static final String JSON_PROPERTY_IP_ADDRESS = "ipAddress";
  @javax.annotation.Nullable
  private String ipAddress;

  public static final String JSON_PROPERTY_IPV6 = "ipv6";
  @javax.annotation.Nullable
  private String ipv6;

  /**
   * IP protocol version.
   */
  public enum IpVersionEnum {
    IPV4(String.valueOf("ipv4")),
    
    IPV6(String.valueOf("ipv6"));

    private String value;

    IpVersionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IpVersionEnum fromValue(String value) {
      for (IpVersionEnum b : IpVersionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_IP_VERSION = "ipVersion";
  @javax.annotation.Nullable
  private IpVersionEnum ipVersion = IpVersionEnum.IPV4;

  public static final String JSON_PROPERTY_IP_PREFIX = "ipPrefix";
  @javax.annotation.Nullable
  private String ipPrefix;

  public static final String JSON_PROPERTY_ASN = "asn";
  @javax.annotation.Nullable
  private String asn;

  public static final String JSON_PROPERTY_ORG = "org";
  @javax.annotation.Nullable
  private String org;

  public static final String JSON_PROPERTY_COMPANY = "company";
  @javax.annotation.Nullable
  private String company;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_REGION = "region";
  @javax.annotation.Nullable
  private String region;

  public static final String JSON_PROPERTY_CITY = "city";
  @javax.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  @javax.annotation.Nullable
  private String postalCode;

  public IpInfo() { 
  }

  public IpInfo ipAddress(@javax.annotation.Nullable String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

  /**
   * IP address of the customer, client, or user that initiated the request. Each octet must be between 0 and 255. 
   * @return ipAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIpAddress() {
    return ipAddress;
  }


  @JsonProperty(JSON_PROPERTY_IP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpAddress(@javax.annotation.Nullable String ipAddress) {
    this.ipAddress = ipAddress;
  }


  public IpInfo ipv6(@javax.annotation.Nullable String ipv6) {
    this.ipv6 = ipv6;
    return this;
  }

  /**
   * IPv6 address.
   * @return ipv6
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IPV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIpv6() {
    return ipv6;
  }


  @JsonProperty(JSON_PROPERTY_IPV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpv6(@javax.annotation.Nullable String ipv6) {
    this.ipv6 = ipv6;
  }


  public IpInfo ipVersion(@javax.annotation.Nullable IpVersionEnum ipVersion) {
    this.ipVersion = ipVersion;
    return this;
  }

  /**
   * IP protocol version.
   * @return ipVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IP_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IpVersionEnum getIpVersion() {
    return ipVersion;
  }


  @JsonProperty(JSON_PROPERTY_IP_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpVersion(@javax.annotation.Nullable IpVersionEnum ipVersion) {
    this.ipVersion = ipVersion;
  }


  public IpInfo ipPrefix(@javax.annotation.Nullable String ipPrefix) {
    this.ipPrefix = ipPrefix;
    return this;
  }

  /**
   * CIDR, e.g., 198.51.100.0/24 or 2001:db8::/48
   * @return ipPrefix
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IP_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIpPrefix() {
    return ipPrefix;
  }


  @JsonProperty(JSON_PROPERTY_IP_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpPrefix(@javax.annotation.Nullable String ipPrefix) {
    this.ipPrefix = ipPrefix;
  }


  public IpInfo asn(@javax.annotation.Nullable String asn) {
    this.asn = asn;
    return this;
  }

  /**
   * Autonomous System Number (ASN) of the IP address.
   * @return asn
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAsn() {
    return asn;
  }


  @JsonProperty(JSON_PROPERTY_ASN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAsn(@javax.annotation.Nullable String asn) {
    this.asn = asn;
  }


  public IpInfo org(@javax.annotation.Nullable String org) {
    this.org = org;
    return this;
  }

  /**
   * Organization associated with the IP address.
   * @return org
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOrg() {
    return org;
  }


  @JsonProperty(JSON_PROPERTY_ORG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrg(@javax.annotation.Nullable String org) {
    this.org = org;
  }


  public IpInfo company(@javax.annotation.Nullable String company) {
    this.company = company;
    return this;
  }

  /**
   * Company associated with the IP address.
   * @return company
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCompany() {
    return company;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompany(@javax.annotation.Nullable String company) {
    this.company = company;
  }


  public IpInfo country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * ISO 3166-1 alpha-2 country code.
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public IpInfo region(@javax.annotation.Nullable String region) {
    this.region = region;
    return this;
  }

  /**
   * Region associated with the IP address.
   * @return region
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRegion() {
    return region;
  }


  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegion(@javax.annotation.Nullable String region) {
    this.region = region;
  }


  public IpInfo city(@javax.annotation.Nullable String city) {
    this.city = city;
    return this;
  }

  /**
   * City associated with the IP address.
   * @return city
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@javax.annotation.Nullable String city) {
    this.city = city;
  }


  public IpInfo postalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  /**
   * Postal code associated with the IP address.
   * @return postalCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPostalCode() {
    return postalCode;
  }


  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = postalCode;
  }


  /**
   * Return true if this IpInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IpInfo ipInfo = (IpInfo) o;
    return Objects.equals(this.ipAddress, ipInfo.ipAddress) &&
        Objects.equals(this.ipv6, ipInfo.ipv6) &&
        Objects.equals(this.ipVersion, ipInfo.ipVersion) &&
        Objects.equals(this.ipPrefix, ipInfo.ipPrefix) &&
        Objects.equals(this.asn, ipInfo.asn) &&
        Objects.equals(this.org, ipInfo.org) &&
        Objects.equals(this.company, ipInfo.company) &&
        Objects.equals(this.country, ipInfo.country) &&
        Objects.equals(this.region, ipInfo.region) &&
        Objects.equals(this.city, ipInfo.city) &&
        Objects.equals(this.postalCode, ipInfo.postalCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ipAddress, ipv6, ipVersion, ipPrefix, asn, org, company, country, region, city, postalCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IpInfo {\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    ipv6: ").append(toIndentedString(ipv6)).append("\n");
    sb.append("    ipVersion: ").append(toIndentedString(ipVersion)).append("\n");
    sb.append("    ipPrefix: ").append(toIndentedString(ipPrefix)).append("\n");
    sb.append("    asn: ").append(toIndentedString(asn)).append("\n");
    sb.append("    org: ").append(toIndentedString(org)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `ipAddress` to the URL query string
    if (getIpAddress() != null) {
      joiner.add(String.format("%sipAddress%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIpAddress()))));
    }

    // add `ipv6` to the URL query string
    if (getIpv6() != null) {
      joiner.add(String.format("%sipv6%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIpv6()))));
    }

    // add `ipVersion` to the URL query string
    if (getIpVersion() != null) {
      joiner.add(String.format("%sipVersion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIpVersion()))));
    }

    // add `ipPrefix` to the URL query string
    if (getIpPrefix() != null) {
      joiner.add(String.format("%sipPrefix%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIpPrefix()))));
    }

    // add `asn` to the URL query string
    if (getAsn() != null) {
      joiner.add(String.format("%sasn%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAsn()))));
    }

    // add `org` to the URL query string
    if (getOrg() != null) {
      joiner.add(String.format("%sorg%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrg()))));
    }

    // add `company` to the URL query string
    if (getCompany() != null) {
      joiner.add(String.format("%scompany%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompany()))));
    }

    // add `country` to the URL query string
    if (getCountry() != null) {
      joiner.add(String.format("%scountry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCountry()))));
    }

    // add `region` to the URL query string
    if (getRegion() != null) {
      joiner.add(String.format("%sregion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRegion()))));
    }

    // add `city` to the URL query string
    if (getCity() != null) {
      joiner.add(String.format("%scity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCity()))));
    }

    // add `postalCode` to the URL query string
    if (getPostalCode() != null) {
      joiner.add(String.format("%spostalCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPostalCode()))));
    }

    return joiner.toString();
  }
}
