/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Merchant context for the purchase.
 */
@JsonPropertyOrder({
  MerchantContext.JSON_PROPERTY_MCC,
  MerchantContext.JSON_PROPERTY_MERCHANT_COUNTRY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class MerchantContext {
  public static final String JSON_PROPERTY_MCC = "mcc";
  @javax.annotation.Nullable
  private String mcc;

  public static final String JSON_PROPERTY_MERCHANT_COUNTRY = "merchantCountry";
  @javax.annotation.Nullable
  private String merchantCountry;

  public MerchantContext() { 
  }

  public MerchantContext mcc(@javax.annotation.Nullable String mcc) {
    this.mcc = mcc;
    return this;
  }

  /**
   * Merchant Category Code (MCC) for the merchant.
   * @return mcc
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MCC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMcc() {
    return mcc;
  }


  @JsonProperty(JSON_PROPERTY_MCC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMcc(@javax.annotation.Nullable String mcc) {
    this.mcc = mcc;
  }


  public MerchantContext merchantCountry(@javax.annotation.Nullable String merchantCountry) {
    this.merchantCountry = merchantCountry;
    return this;
  }

  /**
   * ISO 3166-1 alpha-2 country code.
   * @return merchantCountry
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMerchantCountry() {
    return merchantCountry;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantCountry(@javax.annotation.Nullable String merchantCountry) {
    this.merchantCountry = merchantCountry;
  }


  /**
   * Return true if this MerchantContext object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantContext merchantContext = (MerchantContext) o;
    return Objects.equals(this.mcc, merchantContext.mcc) &&
        Objects.equals(this.merchantCountry, merchantContext.merchantCountry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mcc, merchantCountry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantContext {\n");
    sb.append("    mcc: ").append(toIndentedString(mcc)).append("\n");
    sb.append("    merchantCountry: ").append(toIndentedString(merchantCountry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `mcc` to the URL query string
    if (getMcc() != null) {
      joiner.add(String.format("%smcc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMcc()))));
    }

    // add `merchantCountry` to the URL query string
    if (getMerchantCountry() != null) {
      joiner.add(String.format("%smerchantCountry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMerchantCountry()))));
    }

    return joiner.toString();
  }
}
