/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Order context for the purchase.
 */
@JsonPropertyOrder({
  OrderContext.JSON_PROPERTY_ORDER_ID,
  OrderContext.JSON_PROPERTY_ORDER_TOTAL,
  OrderContext.JSON_PROPERTY_SHIPPING_METHOD,
  OrderContext.JSON_PROPERTY_LINE_ITEM_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class OrderContext {
  public static final String JSON_PROPERTY_ORDER_ID = "orderId";
  @javax.annotation.Nullable
  private String orderId;

  public static final String JSON_PROPERTY_ORDER_TOTAL = "orderTotal";
  @javax.annotation.Nullable
  private Float orderTotal;

  /**
   * Shipping method for the order.
   */
  public enum ShippingMethodEnum {
    DIGITAL(String.valueOf("digital")),
    
    SHIP(String.valueOf("ship")),
    
    BOPIS(String.valueOf("bopis"));

    private String value;

    ShippingMethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ShippingMethodEnum fromValue(String value) {
      for (ShippingMethodEnum b : ShippingMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SHIPPING_METHOD = "shippingMethod";
  @javax.annotation.Nullable
  private ShippingMethodEnum shippingMethod;

  public static final String JSON_PROPERTY_LINE_ITEM_COUNT = "lineItemCount";
  @javax.annotation.Nullable
  private Integer lineItemCount;

  public OrderContext() { 
  }

  public OrderContext orderId(@javax.annotation.Nullable String orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Unique identifier for the order.
   * @return orderId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOrderId() {
    return orderId;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderId(@javax.annotation.Nullable String orderId) {
    this.orderId = orderId;
  }


  public OrderContext orderTotal(@javax.annotation.Nullable Float orderTotal) {
    this.orderTotal = orderTotal;
    return this;
  }

  /**
   * Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
   * minimum: 0.01
   * maximum: 1.0E+7
   * @return orderTotal
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Float getOrderTotal() {
    return orderTotal;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderTotal(@javax.annotation.Nullable Float orderTotal) {
    this.orderTotal = orderTotal;
  }


  public OrderContext shippingMethod(@javax.annotation.Nullable ShippingMethodEnum shippingMethod) {
    this.shippingMethod = shippingMethod;
    return this;
  }

  /**
   * Shipping method for the order.
   * @return shippingMethod
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ShippingMethodEnum getShippingMethod() {
    return shippingMethod;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingMethod(@javax.annotation.Nullable ShippingMethodEnum shippingMethod) {
    this.shippingMethod = shippingMethod;
  }


  public OrderContext lineItemCount(@javax.annotation.Nullable Integer lineItemCount) {
    this.lineItemCount = lineItemCount;
    return this;
  }

  /**
   * Number of items in the order.
   * minimum: 0
   * maximum: 100
   * @return lineItemCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINE_ITEM_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLineItemCount() {
    return lineItemCount;
  }


  @JsonProperty(JSON_PROPERTY_LINE_ITEM_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLineItemCount(@javax.annotation.Nullable Integer lineItemCount) {
    this.lineItemCount = lineItemCount;
  }


  /**
   * Return true if this OrderContext object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderContext orderContext = (OrderContext) o;
    return Objects.equals(this.orderId, orderContext.orderId) &&
        Objects.equals(this.orderTotal, orderContext.orderTotal) &&
        Objects.equals(this.shippingMethod, orderContext.shippingMethod) &&
        Objects.equals(this.lineItemCount, orderContext.lineItemCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, orderTotal, shippingMethod, lineItemCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderContext {\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderTotal: ").append(toIndentedString(orderTotal)).append("\n");
    sb.append("    shippingMethod: ").append(toIndentedString(shippingMethod)).append("\n");
    sb.append("    lineItemCount: ").append(toIndentedString(lineItemCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `orderId` to the URL query string
    if (getOrderId() != null) {
      joiner.add(String.format("%sorderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrderId()))));
    }

    // add `orderTotal` to the URL query string
    if (getOrderTotal() != null) {
      joiner.add(String.format("%sorderTotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrderTotal()))));
    }

    // add `shippingMethod` to the URL query string
    if (getShippingMethod() != null) {
      joiner.add(String.format("%sshippingMethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShippingMethod()))));
    }

    // add `lineItemCount` to the URL query string
    if (getLineItemCount() != null) {
      joiner.add(String.format("%slineItemCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLineItemCount()))));
    }

    return joiner.toString();
  }
}
