/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Authorization outcome details.
 */
@JsonPropertyOrder({
  PaymentAuthorizationOutcome.JSON_PROPERTY_APPROVED,
  PaymentAuthorizationOutcome.JSON_PROPERTY_RESPONSE_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class PaymentAuthorizationOutcome {
  public static final String JSON_PROPERTY_APPROVED = "approved";
  @javax.annotation.Nullable
  private Boolean approved;

  public static final String JSON_PROPERTY_RESPONSE_CODE = "responseCode";
  @javax.annotation.Nullable
  private String responseCode;

  public PaymentAuthorizationOutcome() { 
  }

  public PaymentAuthorizationOutcome approved(@javax.annotation.Nullable Boolean approved) {
    this.approved = approved;
    return this;
  }

  /**
   * Indicates whether authorization was approved.
   * @return approved
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APPROVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getApproved() {
    return approved;
  }


  @JsonProperty(JSON_PROPERTY_APPROVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApproved(@javax.annotation.Nullable Boolean approved) {
    this.approved = approved;
  }


  public PaymentAuthorizationOutcome responseCode(@javax.annotation.Nullable String responseCode) {
    this.responseCode = responseCode;
    return this;
  }

  /**
   * Authorization response code.
   * @return responseCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getResponseCode() {
    return responseCode;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseCode(@javax.annotation.Nullable String responseCode) {
    this.responseCode = responseCode;
  }


  /**
   * Return true if this PaymentAuthorizationOutcome object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentAuthorizationOutcome paymentAuthorizationOutcome = (PaymentAuthorizationOutcome) o;
    return Objects.equals(this.approved, paymentAuthorizationOutcome.approved) &&
        Objects.equals(this.responseCode, paymentAuthorizationOutcome.responseCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approved, responseCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentAuthorizationOutcome {\n");
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("    responseCode: ").append(toIndentedString(responseCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `approved` to the URL query string
    if (getApproved() != null) {
      joiner.add(String.format("%sapproved%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getApproved()))));
    }

    // add `responseCode` to the URL query string
    if (getResponseCode() != null) {
      joiner.add(String.format("%sresponseCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResponseCode()))));
    }

    return joiner.toString();
  }
}
