/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.AvsResultEnum;
import com.alogram.payrisk.v1.models.BankTransfer;
import com.alogram.payrisk.v1.models.Card;
import com.alogram.payrisk.v1.models.CardNetworkEnum;
import com.alogram.payrisk.v1.models.Crypto;
import com.alogram.payrisk.v1.models.CvvResultEnum;
import com.alogram.payrisk.v1.models.Invoice;
import com.alogram.payrisk.v1.models.PaymentCardTypeEnum;
import com.alogram.payrisk.v1.models.PaymentRealtimeTypeEnum;
import com.alogram.payrisk.v1.models.PaymentWalletTypeEnum;
import com.alogram.payrisk.v1.models.Realtime;
import com.alogram.payrisk.v1.models.ScaMethodEnum;
import com.alogram.payrisk.v1.models.ThreeDSData;
import com.alogram.payrisk.v1.models.Wallet;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.alogram.v1.client.ApiClient;
import com.alogram.v1.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
@JsonDeserialize(using = PaymentMethod.PaymentMethodDeserializer.class)
@JsonSerialize(using = PaymentMethod.PaymentMethodSerializer.class)
public class PaymentMethod extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(PaymentMethod.class.getName());

    public static class PaymentMethodSerializer extends StdSerializer<PaymentMethod> {
        public PaymentMethodSerializer(Class<PaymentMethod> t) {
            super(t);
        }

        public PaymentMethodSerializer() {
            this(null);
        }

        @Override
        public void serialize(PaymentMethod value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class PaymentMethodDeserializer extends StdDeserializer<PaymentMethod> {
        public PaymentMethodDeserializer() {
            this(PaymentMethod.class);
        }

        public PaymentMethodDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public PaymentMethod deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize BankTransfer
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransfer.class.equals(Integer.class) || BankTransfer.class.equals(Long.class) || BankTransfer.class.equals(Float.class) || BankTransfer.class.equals(Double.class) || BankTransfer.class.equals(Boolean.class) || BankTransfer.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransfer.class.equals(Integer.class) || BankTransfer.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransfer.class.equals(Float.class) || BankTransfer.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransfer.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransfer.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransfer.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransfer'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransfer'", e);
            }

            // deserialize Card
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Card.class.equals(Integer.class) || Card.class.equals(Long.class) || Card.class.equals(Float.class) || Card.class.equals(Double.class) || Card.class.equals(Boolean.class) || Card.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Card.class.equals(Integer.class) || Card.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Card.class.equals(Float.class) || Card.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Card.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Card.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Card.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Card'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Card'", e);
            }

            // deserialize Crypto
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Crypto.class.equals(Integer.class) || Crypto.class.equals(Long.class) || Crypto.class.equals(Float.class) || Crypto.class.equals(Double.class) || Crypto.class.equals(Boolean.class) || Crypto.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Crypto.class.equals(Integer.class) || Crypto.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Crypto.class.equals(Float.class) || Crypto.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Crypto.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Crypto.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Crypto.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Crypto'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Crypto'", e);
            }

            // deserialize Invoice
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Invoice.class.equals(Integer.class) || Invoice.class.equals(Long.class) || Invoice.class.equals(Float.class) || Invoice.class.equals(Double.class) || Invoice.class.equals(Boolean.class) || Invoice.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Invoice.class.equals(Integer.class) || Invoice.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Invoice.class.equals(Float.class) || Invoice.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Invoice.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Invoice.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Invoice.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Invoice'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Invoice'", e);
            }

            // deserialize Realtime
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Realtime.class.equals(Integer.class) || Realtime.class.equals(Long.class) || Realtime.class.equals(Float.class) || Realtime.class.equals(Double.class) || Realtime.class.equals(Boolean.class) || Realtime.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Realtime.class.equals(Integer.class) || Realtime.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Realtime.class.equals(Float.class) || Realtime.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Realtime.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Realtime.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Realtime.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Realtime'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Realtime'", e);
            }

            // deserialize Wallet
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Wallet.class.equals(Integer.class) || Wallet.class.equals(Long.class) || Wallet.class.equals(Float.class) || Wallet.class.equals(Double.class) || Wallet.class.equals(Boolean.class) || Wallet.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Wallet.class.equals(Integer.class) || Wallet.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Wallet.class.equals(Float.class) || Wallet.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Wallet.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Wallet.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Wallet.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Wallet'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Wallet'", e);
            }

            if (match == 1) {
                PaymentMethod ret = new PaymentMethod();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for PaymentMethod: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public PaymentMethod getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "PaymentMethod cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public PaymentMethod() {
        super("oneOf", Boolean.FALSE);
    }

    public PaymentMethod(BankTransfer o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PaymentMethod(Card o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PaymentMethod(Crypto o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PaymentMethod(Invoice o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PaymentMethod(Realtime o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PaymentMethod(Wallet o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("BankTransfer", BankTransfer.class);
        schemas.put("Card", Card.class);
        schemas.put("Crypto", Crypto.class);
        schemas.put("Invoice", Invoice.class);
        schemas.put("Realtime", Realtime.class);
        schemas.put("Wallet", Wallet.class);
        JSON.registerDescendants(PaymentMethod.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("bank_transfer", BankTransfer.class);
        mappings.put("card", Card.class);
        mappings.put("crypto", Crypto.class);
        mappings.put("invoice", Invoice.class);
        mappings.put("realtime", Realtime.class);
        mappings.put("wallet", Wallet.class);
        mappings.put("PaymentMethod", PaymentMethod.class);
        JSON.registerDiscriminator(PaymentMethod.class, "type", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return PaymentMethod.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * BankTransfer, Card, Crypto, Invoice, Realtime, Wallet
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(BankTransfer.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Card.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Crypto.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Invoice.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Realtime.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Wallet.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be BankTransfer, Card, Crypto, Invoice, Realtime, Wallet");
    }

    /**
     * Get the actual instance, which can be the following:
     * BankTransfer, Card, Crypto, Invoice, Realtime, Wallet
     *
     * @return The actual instance (BankTransfer, Card, Crypto, Invoice, Realtime, Wallet)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransfer`. If the actual instance is not `BankTransfer`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransfer`
     * @throws ClassCastException if the instance is not `BankTransfer`
     */
    public BankTransfer getBankTransfer() throws ClassCastException {
        return (BankTransfer)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Card`. If the actual instance is not `Card`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Card`
     * @throws ClassCastException if the instance is not `Card`
     */
    public Card getCard() throws ClassCastException {
        return (Card)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Crypto`. If the actual instance is not `Crypto`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Crypto`
     * @throws ClassCastException if the instance is not `Crypto`
     */
    public Crypto getCrypto() throws ClassCastException {
        return (Crypto)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Invoice`. If the actual instance is not `Invoice`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Invoice`
     * @throws ClassCastException if the instance is not `Invoice`
     */
    public Invoice getInvoice() throws ClassCastException {
        return (Invoice)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Realtime`. If the actual instance is not `Realtime`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Realtime`
     * @throws ClassCastException if the instance is not `Realtime`
     */
    public Realtime getRealtime() throws ClassCastException {
        return (Realtime)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Wallet`. If the actual instance is not `Wallet`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Wallet`
     * @throws ClassCastException if the instance is not `Wallet`
     */
    public Wallet getWallet() throws ClassCastException {
        return (Wallet)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof Card) {
        if (getActualInstance() != null) {
          joiner.add(((Card)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Wallet) {
        if (getActualInstance() != null) {
          joiner.add(((Wallet)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Realtime) {
        if (getActualInstance() != null) {
          joiner.add(((Realtime)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransfer) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransfer)getActualInstance()).toUrlQueryString(prefix + "one_of_3" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Crypto) {
        if (getActualInstance() != null) {
          joiner.add(((Crypto)getActualInstance()).toUrlQueryString(prefix + "one_of_4" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Invoice) {
        if (getActualInstance() != null) {
          joiner.add(((Invoice)getActualInstance()).toUrlQueryString(prefix + "one_of_5" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}
