/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.ChannelEnum;
import com.alogram.payrisk.v1.models.DeviceInfo;
import com.alogram.payrisk.v1.models.EntryMethodEnum;
import com.alogram.payrisk.v1.models.MerchantContext;
import com.alogram.payrisk.v1.models.OrderContext;
import com.alogram.payrisk.v1.models.PayerTypeEnum;
import com.alogram.payrisk.v1.models.PaymentMethod;
import com.alogram.payrisk.v1.models.StoredCredentialContext;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Purchase details for fraud checks; core fields are common, instrument specifics live in &#x60;paymentMethod&#x60;. 
 */
@JsonPropertyOrder({
  Purchase.JSON_PROPERTY_LOCATION_ID,
  Purchase.JSON_PROPERTY_DEVICE_INFO,
  Purchase.JSON_PROPERTY_TIMESTAMP,
  Purchase.JSON_PROPERTY_TRANSACTION_ID,
  Purchase.JSON_PROPERTY_AMOUNT,
  Purchase.JSON_PROPERTY_CURRENCY,
  Purchase.JSON_PROPERTY_CHANNEL,
  Purchase.JSON_PROPERTY_ENTRY_METHOD,
  Purchase.JSON_PROPERTY_PAYMENT_METHOD,
  Purchase.JSON_PROPERTY_ORDER,
  Purchase.JSON_PROPERTY_PAYER_TYPE,
  Purchase.JSON_PROPERTY_STORED_CREDENTIAL,
  Purchase.JSON_PROPERTY_MERCHANT,
  Purchase.JSON_PROPERTY_METADATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class Purchase {
  public static final String JSON_PROPERTY_LOCATION_ID = "locationId";
  @javax.annotation.Nullable
  private String locationId;

  public static final String JSON_PROPERTY_DEVICE_INFO = "deviceInfo";
  @javax.annotation.Nullable
  private DeviceInfo deviceInfo;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private String timestamp;

  public static final String JSON_PROPERTY_TRANSACTION_ID = "transactionId";
  @javax.annotation.Nullable
  private String transactionId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Float amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nonnull
  private String currency;

  public static final String JSON_PROPERTY_CHANNEL = "channel";
  @javax.annotation.Nullable
  private ChannelEnum channel;

  public static final String JSON_PROPERTY_ENTRY_METHOD = "entryMethod";
  @javax.annotation.Nullable
  private EntryMethodEnum entryMethod;

  public static final String JSON_PROPERTY_PAYMENT_METHOD = "paymentMethod";
  @javax.annotation.Nonnull
  private PaymentMethod paymentMethod;

  public static final String JSON_PROPERTY_ORDER = "order";
  @javax.annotation.Nullable
  private OrderContext order;

  public static final String JSON_PROPERTY_PAYER_TYPE = "payerType";
  @javax.annotation.Nullable
  private PayerTypeEnum payerType = PayerTypeEnum.CONSUMER;

  public static final String JSON_PROPERTY_STORED_CREDENTIAL = "storedCredential";
  @javax.annotation.Nullable
  private StoredCredentialContext storedCredential;

  public static final String JSON_PROPERTY_MERCHANT = "merchant";
  @javax.annotation.Nullable
  private MerchantContext merchant;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private String metadata;

  public Purchase() { 
  }

  public Purchase locationId(@javax.annotation.Nullable String locationId) {
    this.locationId = locationId;
    return this;
  }

  /**
   * Unique identifier for the location where the transaction occurred.
   * @return locationId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLocationId() {
    return locationId;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocationId(@javax.annotation.Nullable String locationId) {
    this.locationId = locationId;
  }


  public Purchase deviceInfo(@javax.annotation.Nullable DeviceInfo deviceInfo) {
    this.deviceInfo = deviceInfo;
    return this;
  }

  /**
   * Get deviceInfo
   * @return deviceInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DeviceInfo getDeviceInfo() {
    return deviceInfo;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceInfo(@javax.annotation.Nullable DeviceInfo deviceInfo) {
    this.deviceInfo = deviceInfo;
  }


  public Purchase timestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * RFC 3339 timestamp with timezone.
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
  }


  public Purchase transactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * A unique identifier for the transaction. Must be between 3 and 50 characters and only contain alphanumeric characters, underscores, or hyphens. 
   * @return transactionId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTransactionId() {
    return transactionId;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
  }


  public Purchase amount(@javax.annotation.Nonnull Float amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
   * minimum: 0.01
   * maximum: 1.0E+7
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Float getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Float amount) {
    this.amount = amount;
  }


  public Purchase currency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * ISO 4217 currency code (e.g., &#39;USD&#39;).
   * @return currency
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public Purchase channel(@javax.annotation.Nullable ChannelEnum channel) {
    this.channel = channel;
    return this;
  }

  /**
   * Get channel
   * @return channel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANNEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ChannelEnum getChannel() {
    return channel;
  }


  @JsonProperty(JSON_PROPERTY_CHANNEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChannel(@javax.annotation.Nullable ChannelEnum channel) {
    this.channel = channel;
  }


  public Purchase entryMethod(@javax.annotation.Nullable EntryMethodEnum entryMethod) {
    this.entryMethod = entryMethod;
    return this;
  }

  /**
   * Get entryMethod
   * @return entryMethod
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTRY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntryMethodEnum getEntryMethod() {
    return entryMethod;
  }


  @JsonProperty(JSON_PROPERTY_ENTRY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntryMethod(@javax.annotation.Nullable EntryMethodEnum entryMethod) {
    this.entryMethod = entryMethod;
  }


  public Purchase paymentMethod(@javax.annotation.Nonnull PaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

  /**
   * Get paymentMethod
   * @return paymentMethod
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PaymentMethod getPaymentMethod() {
    return paymentMethod;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentMethod(@javax.annotation.Nonnull PaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public Purchase order(@javax.annotation.Nullable OrderContext order) {
    this.order = order;
    return this;
  }

  /**
   * Get order
   * @return order
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OrderContext getOrder() {
    return order;
  }


  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrder(@javax.annotation.Nullable OrderContext order) {
    this.order = order;
  }


  public Purchase payerType(@javax.annotation.Nullable PayerTypeEnum payerType) {
    this.payerType = payerType;
    return this;
  }

  /**
   * Get payerType
   * @return payerType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PayerTypeEnum getPayerType() {
    return payerType;
  }


  @JsonProperty(JSON_PROPERTY_PAYER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayerType(@javax.annotation.Nullable PayerTypeEnum payerType) {
    this.payerType = payerType;
  }


  public Purchase storedCredential(@javax.annotation.Nullable StoredCredentialContext storedCredential) {
    this.storedCredential = storedCredential;
    return this;
  }

  /**
   * Get storedCredential
   * @return storedCredential
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STORED_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StoredCredentialContext getStoredCredential() {
    return storedCredential;
  }


  @JsonProperty(JSON_PROPERTY_STORED_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStoredCredential(@javax.annotation.Nullable StoredCredentialContext storedCredential) {
    this.storedCredential = storedCredential;
  }


  public Purchase merchant(@javax.annotation.Nullable MerchantContext merchant) {
    this.merchant = merchant;
    return this;
  }

  /**
   * Get merchant
   * @return merchant
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MerchantContext getMerchant() {
    return merchant;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchant(@javax.annotation.Nullable MerchantContext merchant) {
    this.merchant = merchant;
  }


  public Purchase metadata(@javax.annotation.Nullable String metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable String metadata) {
    this.metadata = metadata;
  }


  /**
   * Return true if this Purchase object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Purchase purchase = (Purchase) o;
    return Objects.equals(this.locationId, purchase.locationId) &&
        Objects.equals(this.deviceInfo, purchase.deviceInfo) &&
        Objects.equals(this.timestamp, purchase.timestamp) &&
        Objects.equals(this.transactionId, purchase.transactionId) &&
        Objects.equals(this.amount, purchase.amount) &&
        Objects.equals(this.currency, purchase.currency) &&
        Objects.equals(this.channel, purchase.channel) &&
        Objects.equals(this.entryMethod, purchase.entryMethod) &&
        Objects.equals(this.paymentMethod, purchase.paymentMethod) &&
        Objects.equals(this.order, purchase.order) &&
        Objects.equals(this.payerType, purchase.payerType) &&
        Objects.equals(this.storedCredential, purchase.storedCredential) &&
        Objects.equals(this.merchant, purchase.merchant) &&
        Objects.equals(this.metadata, purchase.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationId, deviceInfo, timestamp, transactionId, amount, currency, channel, entryMethod, paymentMethod, order, payerType, storedCredential, merchant, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Purchase {\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    deviceInfo: ").append(toIndentedString(deviceInfo)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    entryMethod: ").append(toIndentedString(entryMethod)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    payerType: ").append(toIndentedString(payerType)).append("\n");
    sb.append("    storedCredential: ").append(toIndentedString(storedCredential)).append("\n");
    sb.append("    merchant: ").append(toIndentedString(merchant)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `locationId` to the URL query string
    if (getLocationId() != null) {
      joiner.add(String.format("%slocationId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLocationId()))));
    }

    // add `deviceInfo` to the URL query string
    if (getDeviceInfo() != null) {
      joiner.add(getDeviceInfo().toUrlQueryString(prefix + "deviceInfo" + suffix));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format("%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `transactionId` to the URL query string
    if (getTransactionId() != null) {
      joiner.add(String.format("%stransactionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionId()))));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format("%samount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format("%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `channel` to the URL query string
    if (getChannel() != null) {
      joiner.add(String.format("%schannel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChannel()))));
    }

    // add `entryMethod` to the URL query string
    if (getEntryMethod() != null) {
      joiner.add(String.format("%sentryMethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEntryMethod()))));
    }

    // add `paymentMethod` to the URL query string
    if (getPaymentMethod() != null) {
      joiner.add(getPaymentMethod().toUrlQueryString(prefix + "paymentMethod" + suffix));
    }

    // add `order` to the URL query string
    if (getOrder() != null) {
      joiner.add(getOrder().toUrlQueryString(prefix + "order" + suffix));
    }

    // add `payerType` to the URL query string
    if (getPayerType() != null) {
      joiner.add(String.format("%spayerType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPayerType()))));
    }

    // add `storedCredential` to the URL query string
    if (getStoredCredential() != null) {
      joiner.add(getStoredCredential().toUrlQueryString(prefix + "storedCredential" + suffix));
    }

    // add `merchant` to the URL query string
    if (getMerchant() != null) {
      joiner.add(getMerchant().toUrlQueryString(prefix + "merchant" + suffix));
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      joiner.add(String.format("%smetadata%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetadata()))));
    }

    return joiner.toString();
  }
}
