/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.EntityIds;
import com.alogram.payrisk.v1.models.FraudScore;
import com.alogram.payrisk.v1.models.ReasonDetail;
import com.alogram.payrisk.v1.models.RiskBreakdown;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Fraud score for a specific transaction or entity.
 */
@JsonPropertyOrder({
  ScoreRecord.JSON_PROPERTY_ASSESSMENT_ID,
  ScoreRecord.JSON_PROPERTY_PAYMENT_INTENT_ID,
  ScoreRecord.JSON_PROPERTY_DECISION_AT,
  ScoreRecord.JSON_PROPERTY_DECISION,
  ScoreRecord.JSON_PROPERTY_RISK_SCORE,
  ScoreRecord.JSON_PROPERTY_FRAUD_SCORE,
  ScoreRecord.JSON_PROPERTY_BREAKDOWN,
  ScoreRecord.JSON_PROPERTY_REASONS,
  ScoreRecord.JSON_PROPERTY_ENTITIES,
  ScoreRecord.JSON_PROPERTY_AMOUNT,
  ScoreRecord.JSON_PROPERTY_CURRENCY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class ScoreRecord {
  public static final String JSON_PROPERTY_ASSESSMENT_ID = "assessmentId";
  @javax.annotation.Nonnull
  private String assessmentId;

  public static final String JSON_PROPERTY_PAYMENT_INTENT_ID = "paymentIntentId";
  @javax.annotation.Nullable
  private String paymentIntentId;

  public static final String JSON_PROPERTY_DECISION_AT = "decisionAt";
  @javax.annotation.Nonnull
  private String decisionAt;

  /**
   * The synchronous risk decision for a purchase.
   */
  public enum DecisionEnum {
    APPROVE(String.valueOf("approve")),
    
    REVIEW(String.valueOf("review")),
    
    DECLINE(String.valueOf("decline")),
    
    STEP_UP(String.valueOf("step_up"));

    private String value;

    DecisionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DecisionEnum fromValue(String value) {
      for (DecisionEnum b : DecisionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DECISION = "decision";
  @javax.annotation.Nonnull
  private DecisionEnum decision;

  public static final String JSON_PROPERTY_RISK_SCORE = "riskScore";
  @javax.annotation.Nonnull
  private Float riskScore;

  public static final String JSON_PROPERTY_FRAUD_SCORE = "fraudScore";
  @javax.annotation.Nullable
  private FraudScore fraudScore;

  public static final String JSON_PROPERTY_BREAKDOWN = "breakdown";
  @javax.annotation.Nullable
  private RiskBreakdown breakdown;

  public static final String JSON_PROPERTY_REASONS = "reasons";
  @javax.annotation.Nullable
  private List<ReasonDetail> reasons = new ArrayList<>();

  public static final String JSON_PROPERTY_ENTITIES = "entities";
  @javax.annotation.Nullable
  private EntityIds entities;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nullable
  private Float amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public ScoreRecord() { 
  }

  public ScoreRecord assessmentId(@javax.annotation.Nonnull String assessmentId) {
    this.assessmentId = assessmentId;
    return this;
  }

  /**
   * Universal decision identifier (for purchases, equals paymentIntentId).
   * @return assessmentId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSESSMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAssessmentId() {
    return assessmentId;
  }


  @JsonProperty(JSON_PROPERTY_ASSESSMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssessmentId(@javax.annotation.Nonnull String assessmentId) {
    this.assessmentId = assessmentId;
  }


  public ScoreRecord paymentIntentId(@javax.annotation.Nullable String paymentIntentId) {
    this.paymentIntentId = paymentIntentId;
    return this;
  }

  /**
   * Server-minted unique payment identifier.
   * @return paymentIntentId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_INTENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPaymentIntentId() {
    return paymentIntentId;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_INTENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentIntentId(@javax.annotation.Nullable String paymentIntentId) {
    this.paymentIntentId = paymentIntentId;
  }


  public ScoreRecord decisionAt(@javax.annotation.Nonnull String decisionAt) {
    this.decisionAt = decisionAt;
    return this;
  }

  /**
   * RFC 3339 timestamp with timezone.
   * @return decisionAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DECISION_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDecisionAt() {
    return decisionAt;
  }


  @JsonProperty(JSON_PROPERTY_DECISION_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDecisionAt(@javax.annotation.Nonnull String decisionAt) {
    this.decisionAt = decisionAt;
  }


  public ScoreRecord decision(@javax.annotation.Nonnull DecisionEnum decision) {
    this.decision = decision;
    return this;
  }

  /**
   * The synchronous risk decision for a purchase.
   * @return decision
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DECISION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DecisionEnum getDecision() {
    return decision;
  }


  @JsonProperty(JSON_PROPERTY_DECISION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDecision(@javax.annotation.Nonnull DecisionEnum decision) {
    this.decision = decision;
  }


  public ScoreRecord riskScore(@javax.annotation.Nonnull Float riskScore) {
    this.riskScore = riskScore;
    return this;
  }

  /**
   * Fraud risk score (0.00 - 1.00).
   * minimum: 0.0
   * maximum: 1.0
   * @return riskScore
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RISK_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Float getRiskScore() {
    return riskScore;
  }


  @JsonProperty(JSON_PROPERTY_RISK_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRiskScore(@javax.annotation.Nonnull Float riskScore) {
    this.riskScore = riskScore;
  }


  public ScoreRecord fraudScore(@javax.annotation.Nullable FraudScore fraudScore) {
    this.fraudScore = fraudScore;
    return this;
  }

  /**
   * Get fraudScore
   * @return fraudScore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FRAUD_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FraudScore getFraudScore() {
    return fraudScore;
  }


  @JsonProperty(JSON_PROPERTY_FRAUD_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFraudScore(@javax.annotation.Nullable FraudScore fraudScore) {
    this.fraudScore = fraudScore;
  }


  public ScoreRecord breakdown(@javax.annotation.Nullable RiskBreakdown breakdown) {
    this.breakdown = breakdown;
    return this;
  }

  /**
   * Get breakdown
   * @return breakdown
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BREAKDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RiskBreakdown getBreakdown() {
    return breakdown;
  }


  @JsonProperty(JSON_PROPERTY_BREAKDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBreakdown(@javax.annotation.Nullable RiskBreakdown breakdown) {
    this.breakdown = breakdown;
  }


  public ScoreRecord reasons(@javax.annotation.Nullable List<ReasonDetail> reasons) {
    this.reasons = reasons;
    return this;
  }

  public ScoreRecord addReasonsItem(ReasonDetail reasonsItem) {
    if (this.reasons == null) {
      this.reasons = new ArrayList<>();
    }
    this.reasons.add(reasonsItem);
    return this;
  }

  /**
   * Structured reason details for the score.
   * @return reasons
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REASONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ReasonDetail> getReasons() {
    return reasons;
  }


  @JsonProperty(JSON_PROPERTY_REASONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReasons(@javax.annotation.Nullable List<ReasonDetail> reasons) {
    this.reasons = reasons;
  }


  public ScoreRecord entities(@javax.annotation.Nullable EntityIds entities) {
    this.entities = entities;
    return this;
  }

  /**
   * Get entities
   * @return entities
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EntityIds getEntities() {
    return entities;
  }


  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntities(@javax.annotation.Nullable EntityIds entities) {
    this.entities = entities;
  }


  public ScoreRecord amount(@javax.annotation.Nullable Float amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
   * minimum: 0.01
   * maximum: 1.0E+7
   * @return amount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Float getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(@javax.annotation.Nullable Float amount) {
    this.amount = amount;
  }


  public ScoreRecord currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * ISO 4217 currency code (e.g., &#39;USD&#39;).
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  /**
   * Return true if this ScoreRecord object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScoreRecord scoreRecord = (ScoreRecord) o;
    return Objects.equals(this.assessmentId, scoreRecord.assessmentId) &&
        Objects.equals(this.paymentIntentId, scoreRecord.paymentIntentId) &&
        Objects.equals(this.decisionAt, scoreRecord.decisionAt) &&
        Objects.equals(this.decision, scoreRecord.decision) &&
        Objects.equals(this.riskScore, scoreRecord.riskScore) &&
        Objects.equals(this.fraudScore, scoreRecord.fraudScore) &&
        Objects.equals(this.breakdown, scoreRecord.breakdown) &&
        Objects.equals(this.reasons, scoreRecord.reasons) &&
        Objects.equals(this.entities, scoreRecord.entities) &&
        Objects.equals(this.amount, scoreRecord.amount) &&
        Objects.equals(this.currency, scoreRecord.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assessmentId, paymentIntentId, decisionAt, decision, riskScore, fraudScore, breakdown, reasons, entities, amount, currency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScoreRecord {\n");
    sb.append("    assessmentId: ").append(toIndentedString(assessmentId)).append("\n");
    sb.append("    paymentIntentId: ").append(toIndentedString(paymentIntentId)).append("\n");
    sb.append("    decisionAt: ").append(toIndentedString(decisionAt)).append("\n");
    sb.append("    decision: ").append(toIndentedString(decision)).append("\n");
    sb.append("    riskScore: ").append(toIndentedString(riskScore)).append("\n");
    sb.append("    fraudScore: ").append(toIndentedString(fraudScore)).append("\n");
    sb.append("    breakdown: ").append(toIndentedString(breakdown)).append("\n");
    sb.append("    reasons: ").append(toIndentedString(reasons)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `assessmentId` to the URL query string
    if (getAssessmentId() != null) {
      joiner.add(String.format("%sassessmentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAssessmentId()))));
    }

    // add `paymentIntentId` to the URL query string
    if (getPaymentIntentId() != null) {
      joiner.add(String.format("%spaymentIntentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentIntentId()))));
    }

    // add `decisionAt` to the URL query string
    if (getDecisionAt() != null) {
      joiner.add(String.format("%sdecisionAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDecisionAt()))));
    }

    // add `decision` to the URL query string
    if (getDecision() != null) {
      joiner.add(String.format("%sdecision%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDecision()))));
    }

    // add `riskScore` to the URL query string
    if (getRiskScore() != null) {
      joiner.add(String.format("%sriskScore%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRiskScore()))));
    }

    // add `fraudScore` to the URL query string
    if (getFraudScore() != null) {
      joiner.add(getFraudScore().toUrlQueryString(prefix + "fraudScore" + suffix));
    }

    // add `breakdown` to the URL query string
    if (getBreakdown() != null) {
      joiner.add(getBreakdown().toUrlQueryString(prefix + "breakdown" + suffix));
    }

    // add `reasons` to the URL query string
    if (getReasons() != null) {
      for (int i = 0; i < getReasons().size(); i++) {
        if (getReasons().get(i) != null) {
          joiner.add(getReasons().get(i).toUrlQueryString(String.format("%sreasons%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `entities` to the URL query string
    if (getEntities() != null) {
      joiner.add(getEntities().toUrlQueryString(prefix + "entities" + suffix));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format("%samount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format("%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    return joiner.toString();
  }
}
