/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.ScoreRecord;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * List of fraud scores for a customer.
 */
@JsonPropertyOrder({
  ScoresSuccessResponse.JSON_PROPERTY_SCORES,
  ScoresSuccessResponse.JSON_PROPERTY_NEXT_PAGE_TOKEN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class ScoresSuccessResponse {
  public static final String JSON_PROPERTY_SCORES = "scores";
  @javax.annotation.Nullable
  private List<ScoreRecord> scores = new ArrayList<>();

  public static final String JSON_PROPERTY_NEXT_PAGE_TOKEN = "nextPageToken";
  @javax.annotation.Nullable
  private String nextPageToken;

  public ScoresSuccessResponse() { 
  }

  public ScoresSuccessResponse scores(@javax.annotation.Nullable List<ScoreRecord> scores) {
    this.scores = scores;
    return this;
  }

  public ScoresSuccessResponse addScoresItem(ScoreRecord scoresItem) {
    if (this.scores == null) {
      this.scores = new ArrayList<>();
    }
    this.scores.add(scoresItem);
    return this;
  }

  /**
   * Score records within the requested window.
   * @return scores
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCORES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ScoreRecord> getScores() {
    return scores;
  }


  @JsonProperty(JSON_PROPERTY_SCORES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScores(@javax.annotation.Nullable List<ScoreRecord> scores) {
    this.scores = scores;
  }


  public ScoresSuccessResponse nextPageToken(@javax.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  /**
   * A token for retrieving the next page of results.
   * @return nextPageToken
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEXT_PAGE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNextPageToken() {
    return nextPageToken;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_PAGE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextPageToken(@javax.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  /**
   * Return true if this ScoresSuccessResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScoresSuccessResponse scoresSuccessResponse = (ScoresSuccessResponse) o;
    return Objects.equals(this.scores, scoresSuccessResponse.scores) &&
        Objects.equals(this.nextPageToken, scoresSuccessResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scores, nextPageToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScoresSuccessResponse {\n");
    sb.append("    scores: ").append(toIndentedString(scores)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `scores` to the URL query string
    if (getScores() != null) {
      for (int i = 0; i < getScores().size(); i++) {
        if (getScores().get(i) != null) {
          joiner.add(getScores().get(i).toUrlQueryString(String.format("%sscores%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `nextPageToken` to the URL query string
    if (getNextPageToken() != null) {
      joiner.add(String.format("%snextPageToken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNextPageToken()))));
    }

    return joiner.toString();
  }
}
