/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.EntityIds;
import com.alogram.payrisk.v1.models.Interaction;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Interaction batch signal variant (one or more user interactions).
 */
@JsonPropertyOrder({
  SignalsInteractionVariant.JSON_PROPERTY_SIGNAL_TYPE,
  SignalsInteractionVariant.JSON_PROPERTY_ENTITIES,
  SignalsInteractionVariant.JSON_PROPERTY_INTERACTIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class SignalsInteractionVariant {
  /**
   * Value for interaction signals.
   */
  public enum SignalTypeEnum {
    INTERACTION(String.valueOf("interaction"));

    private String value;

    SignalTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignalTypeEnum fromValue(String value) {
      for (SignalTypeEnum b : SignalTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGNAL_TYPE = "signalType";
  @javax.annotation.Nonnull
  private SignalTypeEnum signalType;

  public static final String JSON_PROPERTY_ENTITIES = "entities";
  @javax.annotation.Nonnull
  private EntityIds entities;

  public static final String JSON_PROPERTY_INTERACTIONS = "interactions";
  @javax.annotation.Nonnull
  private List<Interaction> interactions = new ArrayList<>();

  public SignalsInteractionVariant() { 
  }

  public SignalsInteractionVariant signalType(@javax.annotation.Nonnull SignalTypeEnum signalType) {
    this.signalType = signalType;
    return this;
  }

  /**
   * Value for interaction signals.
   * @return signalType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public SignalTypeEnum getSignalType() {
    return signalType;
  }


  @JsonProperty(JSON_PROPERTY_SIGNAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignalType(@javax.annotation.Nonnull SignalTypeEnum signalType) {
    this.signalType = signalType;
  }


  public SignalsInteractionVariant entities(@javax.annotation.Nonnull EntityIds entities) {
    this.entities = entities;
    return this;
  }

  /**
   * Get entities
   * @return entities
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EntityIds getEntities() {
    return entities;
  }


  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntities(@javax.annotation.Nonnull EntityIds entities) {
    this.entities = entities;
  }


  public SignalsInteractionVariant interactions(@javax.annotation.Nonnull List<Interaction> interactions) {
    this.interactions = interactions;
    return this;
  }

  public SignalsInteractionVariant addInteractionsItem(Interaction interactionsItem) {
    if (this.interactions == null) {
      this.interactions = new ArrayList<>();
    }
    this.interactions.add(interactionsItem);
    return this;
  }

  /**
   * One or more interactions associated with the signal.
   * @return interactions
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INTERACTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Interaction> getInteractions() {
    return interactions;
  }


  @JsonProperty(JSON_PROPERTY_INTERACTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInteractions(@javax.annotation.Nonnull List<Interaction> interactions) {
    this.interactions = interactions;
  }


  /**
   * Return true if this SignalsInteractionVariant object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignalsInteractionVariant signalsInteractionVariant = (SignalsInteractionVariant) o;
    return Objects.equals(this.signalType, signalsInteractionVariant.signalType) &&
        Objects.equals(this.entities, signalsInteractionVariant.entities) &&
        Objects.equals(this.interactions, signalsInteractionVariant.interactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signalType, entities, interactions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignalsInteractionVariant {\n");
    sb.append("    signalType: ").append(toIndentedString(signalType)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    interactions: ").append(toIndentedString(interactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `signalType` to the URL query string
    if (getSignalType() != null) {
      joiner.add(String.format("%ssignalType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSignalType()))));
    }

    // add `entities` to the URL query string
    if (getEntities() != null) {
      joiner.add(getEntities().toUrlQueryString(prefix + "entities" + suffix));
    }

    // add `interactions` to the URL query string
    if (getInteractions() != null) {
      for (int i = 0; i < getInteractions().size(); i++) {
        if (getInteractions().get(i) != null) {
          joiner.add(getInteractions().get(i).toUrlQueryString(String.format("%sinteractions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}
