/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.Account;
import com.alogram.payrisk.v1.models.EntityIds;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Account-level signal variant (single account state snapshot).
 */
@JsonPropertyOrder({
  SignalsAccountVariant.JSON_PROPERTY_SIGNAL_TYPE,
  SignalsAccountVariant.JSON_PROPERTY_ENTITIES,
  SignalsAccountVariant.JSON_PROPERTY_ACCOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class SignalsAccountVariant {
  /**
   * Value for account signals.
   */
  public enum SignalTypeEnum {
    ACCOUNT(String.valueOf("account"));

    private String value;

    SignalTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignalTypeEnum fromValue(String value) {
      for (SignalTypeEnum b : SignalTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGNAL_TYPE = "signalType";
  @javax.annotation.Nonnull
  private SignalTypeEnum signalType;

  public static final String JSON_PROPERTY_ENTITIES = "entities";
  @javax.annotation.Nonnull
  private EntityIds entities;

  public static final String JSON_PROPERTY_ACCOUNT = "account";
  @javax.annotation.Nonnull
  private Account account;

  public SignalsAccountVariant() { 
  }

  public SignalsAccountVariant signalType(@javax.annotation.Nonnull SignalTypeEnum signalType) {
    this.signalType = signalType;
    return this;
  }

  /**
   * Value for account signals.
   * @return signalType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public SignalTypeEnum getSignalType() {
    return signalType;
  }


  @JsonProperty(JSON_PROPERTY_SIGNAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignalType(@javax.annotation.Nonnull SignalTypeEnum signalType) {
    this.signalType = signalType;
  }


  public SignalsAccountVariant entities(@javax.annotation.Nonnull EntityIds entities) {
    this.entities = entities;
    return this;
  }

  /**
   * Get entities
   * @return entities
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EntityIds getEntities() {
    return entities;
  }


  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntities(@javax.annotation.Nonnull EntityIds entities) {
    this.entities = entities;
  }


  public SignalsAccountVariant account(@javax.annotation.Nonnull Account account) {
    this.account = account;
    return this;
  }

  /**
   * Get account
   * @return account
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Account getAccount() {
    return account;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccount(@javax.annotation.Nonnull Account account) {
    this.account = account;
  }


  /**
   * Return true if this SignalsAccountVariant object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignalsAccountVariant signalsAccountVariant = (SignalsAccountVariant) o;
    return Objects.equals(this.signalType, signalsAccountVariant.signalType) &&
        Objects.equals(this.entities, signalsAccountVariant.entities) &&
        Objects.equals(this.account, signalsAccountVariant.account);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signalType, entities, account);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignalsAccountVariant {\n");
    sb.append("    signalType: ").append(toIndentedString(signalType)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `signalType` to the URL query string
    if (getSignalType() != null) {
      joiner.add(String.format("%ssignalType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSignalType()))));
    }

    // add `entities` to the URL query string
    if (getEntities() != null) {
      joiner.add(getEntities().toUrlQueryString(prefix + "entities" + suffix));
    }

    // add `account` to the URL query string
    if (getAccount() != null) {
      joiner.add(getAccount().toUrlQueryString(prefix + "account" + suffix));
    }

    return joiner.toString();
  }
}
