/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.Account;
import com.alogram.payrisk.v1.models.EntityIds;
import com.alogram.payrisk.v1.models.Interaction;
import com.alogram.payrisk.v1.models.SignalsAccountVariant;
import com.alogram.payrisk.v1.models.SignalsInteractionVariant;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.alogram.v1.client.ApiClient;
import com.alogram.v1.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
@JsonDeserialize(using = SignalsRequest.SignalsRequestDeserializer.class)
@JsonSerialize(using = SignalsRequest.SignalsRequestSerializer.class)
public class SignalsRequest extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(SignalsRequest.class.getName());

    public static class SignalsRequestSerializer extends StdSerializer<SignalsRequest> {
        public SignalsRequestSerializer(Class<SignalsRequest> t) {
            super(t);
        }

        public SignalsRequestSerializer() {
            this(null);
        }

        @Override
        public void serialize(SignalsRequest value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class SignalsRequestDeserializer extends StdDeserializer<SignalsRequest> {
        public SignalsRequestDeserializer() {
            this(SignalsRequest.class);
        }

        public SignalsRequestDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public SignalsRequest deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize SignalsAccountVariant
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignalsAccountVariant.class.equals(Integer.class) || SignalsAccountVariant.class.equals(Long.class) || SignalsAccountVariant.class.equals(Float.class) || SignalsAccountVariant.class.equals(Double.class) || SignalsAccountVariant.class.equals(Boolean.class) || SignalsAccountVariant.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignalsAccountVariant.class.equals(Integer.class) || SignalsAccountVariant.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignalsAccountVariant.class.equals(Float.class) || SignalsAccountVariant.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignalsAccountVariant.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignalsAccountVariant.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignalsAccountVariant.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignalsAccountVariant'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignalsAccountVariant'", e);
            }

            // deserialize SignalsInteractionVariant
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignalsInteractionVariant.class.equals(Integer.class) || SignalsInteractionVariant.class.equals(Long.class) || SignalsInteractionVariant.class.equals(Float.class) || SignalsInteractionVariant.class.equals(Double.class) || SignalsInteractionVariant.class.equals(Boolean.class) || SignalsInteractionVariant.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignalsInteractionVariant.class.equals(Integer.class) || SignalsInteractionVariant.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignalsInteractionVariant.class.equals(Float.class) || SignalsInteractionVariant.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignalsInteractionVariant.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignalsInteractionVariant.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignalsInteractionVariant.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignalsInteractionVariant'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignalsInteractionVariant'", e);
            }

            if (match == 1) {
                SignalsRequest ret = new SignalsRequest();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for SignalsRequest: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public SignalsRequest getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "SignalsRequest cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public SignalsRequest() {
        super("oneOf", Boolean.FALSE);
    }

    public SignalsRequest(SignalsAccountVariant o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public SignalsRequest(SignalsInteractionVariant o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("SignalsAccountVariant", SignalsAccountVariant.class);
        schemas.put("SignalsInteractionVariant", SignalsInteractionVariant.class);
        JSON.registerDescendants(SignalsRequest.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("account", SignalsAccountVariant.class);
        mappings.put("interaction", SignalsInteractionVariant.class);
        mappings.put("SignalsRequest", SignalsRequest.class);
        JSON.registerDiscriminator(SignalsRequest.class, "signalType", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return SignalsRequest.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * SignalsAccountVariant, SignalsInteractionVariant
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(SignalsAccountVariant.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignalsInteractionVariant.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be SignalsAccountVariant, SignalsInteractionVariant");
    }

    /**
     * Get the actual instance, which can be the following:
     * SignalsAccountVariant, SignalsInteractionVariant
     *
     * @return The actual instance (SignalsAccountVariant, SignalsInteractionVariant)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignalsAccountVariant`. If the actual instance is not `SignalsAccountVariant`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignalsAccountVariant`
     * @throws ClassCastException if the instance is not `SignalsAccountVariant`
     */
    public SignalsAccountVariant getSignalsAccountVariant() throws ClassCastException {
        return (SignalsAccountVariant)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignalsInteractionVariant`. If the actual instance is not `SignalsInteractionVariant`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignalsInteractionVariant`
     * @throws ClassCastException if the instance is not `SignalsInteractionVariant`
     */
    public SignalsInteractionVariant getSignalsInteractionVariant() throws ClassCastException {
        return (SignalsInteractionVariant)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof SignalsAccountVariant) {
        if (getActualInstance() != null) {
          joiner.add(((SignalsAccountVariant)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignalsInteractionVariant) {
        if (getActualInstance() != null) {
          joiner.add(((SignalsInteractionVariant)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}
