/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.alogram.payrisk.v1.models.PurchaseInitiatorEnum;
import com.alogram.payrisk.v1.models.PurchaseSequenceEnum;
import com.alogram.payrisk.v1.models.PurchaseUsageEnum;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * Minimal stored-credential / recurrence context.
 */
@JsonPropertyOrder({
  StoredCredentialContext.JSON_PROPERTY_USAGE,
  StoredCredentialContext.JSON_PROPERTY_SEQUENCE,
  StoredCredentialContext.JSON_PROPERTY_INITIATOR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class StoredCredentialContext {
  public static final String JSON_PROPERTY_USAGE = "usage";
  @javax.annotation.Nullable
  private PurchaseUsageEnum usage = PurchaseUsageEnum.ONE_TIME;

  public static final String JSON_PROPERTY_SEQUENCE = "sequence";
  @javax.annotation.Nullable
  private PurchaseSequenceEnum sequence;

  public static final String JSON_PROPERTY_INITIATOR = "initiator";
  @javax.annotation.Nullable
  private PurchaseInitiatorEnum initiator;

  public StoredCredentialContext() { 
  }

  public StoredCredentialContext usage(@javax.annotation.Nullable PurchaseUsageEnum usage) {
    this.usage = usage;
    return this;
  }

  /**
   * Get usage
   * @return usage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PurchaseUsageEnum getUsage() {
    return usage;
  }


  @JsonProperty(JSON_PROPERTY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsage(@javax.annotation.Nullable PurchaseUsageEnum usage) {
    this.usage = usage;
  }


  public StoredCredentialContext sequence(@javax.annotation.Nullable PurchaseSequenceEnum sequence) {
    this.sequence = sequence;
    return this;
  }

  /**
   * Get sequence
   * @return sequence
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEQUENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PurchaseSequenceEnum getSequence() {
    return sequence;
  }


  @JsonProperty(JSON_PROPERTY_SEQUENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSequence(@javax.annotation.Nullable PurchaseSequenceEnum sequence) {
    this.sequence = sequence;
  }


  public StoredCredentialContext initiator(@javax.annotation.Nullable PurchaseInitiatorEnum initiator) {
    this.initiator = initiator;
    return this;
  }

  /**
   * Get initiator
   * @return initiator
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INITIATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PurchaseInitiatorEnum getInitiator() {
    return initiator;
  }


  @JsonProperty(JSON_PROPERTY_INITIATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInitiator(@javax.annotation.Nullable PurchaseInitiatorEnum initiator) {
    this.initiator = initiator;
  }


  /**
   * Return true if this StoredCredentialContext object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoredCredentialContext storedCredentialContext = (StoredCredentialContext) o;
    return Objects.equals(this.usage, storedCredentialContext.usage) &&
        Objects.equals(this.sequence, storedCredentialContext.sequence) &&
        Objects.equals(this.initiator, storedCredentialContext.initiator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usage, sequence, initiator);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoredCredentialContext {\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    initiator: ").append(toIndentedString(initiator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `usage` to the URL query string
    if (getUsage() != null) {
      joiner.add(String.format("%susage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUsage()))));
    }

    // add `sequence` to the URL query string
    if (getSequence() != null) {
      joiner.add(String.format("%ssequence%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSequence()))));
    }

    // add `initiator` to the URL query string
    if (getInitiator() != null) {
      joiner.add(String.format("%sinitiator%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInitiator()))));
    }

    return joiner.toString();
  }
}
