/*
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alogram.payrisk.v1.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.alogram.v1.client.ApiClient;
/**
 * 3D Secure (3DS) data for card transactions.
 */
@JsonPropertyOrder({
  ThreeDSData.JSON_PROPERTY_VERSION,
  ThreeDSData.JSON_PROPERTY_ECI,
  ThreeDSData.JSON_PROPERTY_FLOW,
  ThreeDSData.JSON_PROPERTY_LIABILITY_SHIFT,
  ThreeDSData.JSON_PROPERTY_CAVV_PRESENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T04:12:17.824225483Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class ThreeDSData {
  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nullable
  private String version;

  public static final String JSON_PROPERTY_ECI = "eci";
  @javax.annotation.Nullable
  private String eci;

  /**
   * The flow of the 3D Secure authentication. &#39;frictionless&#39; means no challenge was presented to the cardholder, &#39;challenge&#39; means the cardholder was challenged. 
   */
  public enum FlowEnum {
    FRICTIONLESS(String.valueOf("frictionless")),
    
    CHALLENGE(String.valueOf("challenge"));

    private String value;

    FlowEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FlowEnum fromValue(String value) {
      for (FlowEnum b : FlowEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FLOW = "flow";
  @javax.annotation.Nullable
  private FlowEnum flow;

  public static final String JSON_PROPERTY_LIABILITY_SHIFT = "liabilityShift";
  @javax.annotation.Nullable
  private Boolean liabilityShift;

  public static final String JSON_PROPERTY_CAVV_PRESENT = "cavvPresent";
  @javax.annotation.Nullable
  private Boolean cavvPresent;

  public ThreeDSData() { 
  }

  public ThreeDSData version(@javax.annotation.Nullable String version) {
    this.version = version;
    return this;
  }

  /**
   * The version of the 3D Secure protocol used (e.g., &#39;2.2.0&#39;).
   * @return version
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@javax.annotation.Nullable String version) {
    this.version = version;
  }


  public ThreeDSData eci(@javax.annotation.Nullable String eci) {
    this.eci = eci;
    return this;
  }

  /**
   * Electronic Commerce Indicator. Values indicate the outcome of 3D Secure authentication. 
   * @return eci
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ECI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEci() {
    return eci;
  }


  @JsonProperty(JSON_PROPERTY_ECI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEci(@javax.annotation.Nullable String eci) {
    this.eci = eci;
  }


  public ThreeDSData flow(@javax.annotation.Nullable FlowEnum flow) {
    this.flow = flow;
    return this;
  }

  /**
   * The flow of the 3D Secure authentication. &#39;frictionless&#39; means no challenge was presented to the cardholder, &#39;challenge&#39; means the cardholder was challenged. 
   * @return flow
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FlowEnum getFlow() {
    return flow;
  }


  @JsonProperty(JSON_PROPERTY_FLOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlow(@javax.annotation.Nullable FlowEnum flow) {
    this.flow = flow;
  }


  public ThreeDSData liabilityShift(@javax.annotation.Nullable Boolean liabilityShift) {
    this.liabilityShift = liabilityShift;
    return this;
  }

  /**
   * Indicates whether liability for chargebacks has shifted to the issuer (true) or remains with the merchant (false). 
   * @return liabilityShift
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIABILITY_SHIFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getLiabilityShift() {
    return liabilityShift;
  }


  @JsonProperty(JSON_PROPERTY_LIABILITY_SHIFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLiabilityShift(@javax.annotation.Nullable Boolean liabilityShift) {
    this.liabilityShift = liabilityShift;
  }


  public ThreeDSData cavvPresent(@javax.annotation.Nullable Boolean cavvPresent) {
    this.cavvPresent = cavvPresent;
    return this;
  }

  /**
   * Indicates whether the Cardholder Authentication Verification Value (CAVV) was present in the 3DS message. 
   * @return cavvPresent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAVV_PRESENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCavvPresent() {
    return cavvPresent;
  }


  @JsonProperty(JSON_PROPERTY_CAVV_PRESENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCavvPresent(@javax.annotation.Nullable Boolean cavvPresent) {
    this.cavvPresent = cavvPresent;
  }


  /**
   * Return true if this ThreeDSData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreeDSData threeDSData = (ThreeDSData) o;
    return Objects.equals(this.version, threeDSData.version) &&
        Objects.equals(this.eci, threeDSData.eci) &&
        Objects.equals(this.flow, threeDSData.flow) &&
        Objects.equals(this.liabilityShift, threeDSData.liabilityShift) &&
        Objects.equals(this.cavvPresent, threeDSData.cavvPresent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, eci, flow, liabilityShift, cavvPresent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreeDSData {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    eci: ").append(toIndentedString(eci)).append("\n");
    sb.append("    flow: ").append(toIndentedString(flow)).append("\n");
    sb.append("    liabilityShift: ").append(toIndentedString(liabilityShift)).append("\n");
    sb.append("    cavvPresent: ").append(toIndentedString(cavvPresent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `version` to the URL query string
    if (getVersion() != null) {
      joiner.add(String.format("%sversion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersion()))));
    }

    // add `eci` to the URL query string
    if (getEci() != null) {
      joiner.add(String.format("%seci%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEci()))));
    }

    // add `flow` to the URL query string
    if (getFlow() != null) {
      joiner.add(String.format("%sflow%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlow()))));
    }

    // add `liabilityShift` to the URL query string
    if (getLiabilityShift() != null) {
      joiner.add(String.format("%sliabilityShift%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLiabilityShift()))));
    }

    // add `cavvPresent` to the URL query string
    if (getCavvPresent() != null) {
      joiner.add(String.format("%scavvPresent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCavvPresent()))));
    }

    return joiner.toString();
  }
}
